services:
  feedlr-migrate:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile.migrate
    pull_policy: always
    command: migrate apply --allow-dirty --dir "file:///migrations" --tx-mode all --url "sqlite://${DATABASE_PATH}?_fk=1"
    volumes:
      - ${DATABASE_DIR}:/data
    networks:
      - dokploy-network

  feedlr-service:
    build:
      dockerfile: Dockerfile
    environment:
      - PORT=3000 # the port does not matter, but it needs to match Traefik labels. we set it here explicitly in order to avoid any issues
    expose:
      - 3000
    env_file:
      - .env
    volumes:
      - ${DATABASE_DIR}:/data
    restart: always
    depends_on:
      feedlr-migrate:
        condition: service_completed_successfully
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feedlr-compose-{$ENVIRONMENT}.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.feedlr-compose-{$ENVIRONMENT}.entrypoints=websecure"
      - "traefik.http.routers.feedlr-compose-{$ENVIRONMENT}.tls.certResolver=letsencrypt"
      - "traefik.http.services.feedlr-compose-{$ENVIRONMENT}.loadbalancer.server.port=3000"

networks:
  dokploy-network:
    external: true
