output = "internal/database/models"
wipe = true
no-tests = false
add-enum-types = true


[sqlite3]
blacklist = ["atlas_schema_revisions"]

[aliases.tables.user_subscriptions.relationships.user_subscriptions_user_id_fkey]
foreign = "Subscriptions"
