version: 3

# User by --watch
interval: '500ms'

dotenv: ['.env']

vars:
  PRISMA_CLIENT: 'go run github.com/steebchen/prisma-client-go'
  COMMIT_ID:
    sh: git rev-parse --short HEAD || echo "unknown"

tasks:
  dev:
    desc: Run the application in development mode with hot reload
    cmds:
      - air
  test:
    desc: Run tests
    cmds:
      - go test ./... -v          
  upgrade:
    desc: Upgrade dependencies
    cmds:
      - go get -u ./...
  generate:
    desc: Run go generate
    cmds:
      - go generate ./...
  generate:internal:
    desc: Run go generate
    cmds:
      - go generate ./internal/...

  build:fast:
    desc: Build the application without go generate
    env:
      BUILD_MODE: true
      CGO_ENABLED: 0
      GOOS: linux
    cmds:
      - go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o {{ .CLI_ARGS | default "app" }} .
  build:full:
    desc: Build the application with go generate
    aliases: [build]
    deps: [generate]
    cmds:
      - task: build:fast
  build:docker:
    desc: Build the application without generating styles
    deps: [generate:internal]
    cmds:
      - task: build:fast
  build:image:
    desc: Build the Docker image
    cmds:
      - docker build --progress=plain --platform linux/amd64 -t {{ .CLI_ARGS | default "github.com/cufee/feedlr-yt" }} .
  style:generate:
    desc: Generate the CSS files
    cmds:
      - rm -rf ./assets/css/style.*.css*
      - npm install && npx tailwindcss -i ./assets/css/input.css -o ./assets/css/style.{{.COMMIT_ID}}.css --minify
