version: 3

# User by --watch
interval: '500ms'

dotenv: ['.env']
vars:
  DATABASE_PATH: $DATABASE_PATH
  COMMIT_ID:
    sh: git rev-parse --short HEAD || echo "unknown"

tasks:
  dev:
    desc: Run the application in development mode with hot reload
    cmds:
      - air
  test:
    desc: Run tests
    cmds:
      - go test ./... -v          
  upgrade:
    desc: Upgrade dependencies
    cmds:
      - go get -u ./...
  generate:
    desc: Run go generate
    cmds:
      - go generate ./...
      - sqlboiler sqlite3

  migrate:
    desc: generate migrations
    cmd: atlas migrate hash --dir "file://internal/database/migrations" && atlas migrate diff {{.CLI_ARGS}} --dir "file://internal/database/migrations" --to file://schema.hcl --dev-url "sqlite://file?mode=memory&_fk=1"
  migrate-apply:
    desc: apply migrations using atlas
    cmds:
      # variables will be pulled from global vars declaration unless overwritten in the task call
      - echo "Applying migrations to {{.DATABASE_PATH}}"
      - atlas migrate apply --allow-dirty --dir "file://internal/database/migrations" --tx-mode all --url "sqlite://{{.DATABASE_PATH}}?_fk=1"

  build:fast:
    desc: Build the application without go generate
    env:
      BUILD_MODE: true
      CGO_ENABLED: 0
      GOOS: linux
    cmds:
      - go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o {{ .CLI_ARGS | default "app" }} .
  build:full:
    desc: Build the application with go generate
    aliases: [build]
    deps: [generate]
    cmds:
      - task: build:fast
  build:docker:
    desc: Build the application without generating styles
    deps: [generate]
    cmds:
      - task: build:fast
  build:image:
    desc: Build the Docker image
    cmds:
      - docker build --progress=plain --platform linux/amd64 -t {{ .CLI_ARGS | default "github.com/cufee/feedlr-yt" }} .