version: 3

dotenv: ['.env']

vars:
  PRISMA_CLIENT: 'go run github.com/steebchen/prisma-client-go'

tasks:
  dev:
    deps: [generate]
    cmds:
      - air
  generate:
    cmds:
      - go generate ./...
  build:
    deps: [generate]
    env:
      BUILD_MODE: true
      CGO_ENABLED: 0
      GOOS: linux
    cmds:
      - go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o app .
  test:
    cmds:
      - go test ./... -v          
  upgrade:
    cmds:
      - go get -u ./...

  style:generate:
    cmds:
      - npm install && npx tailwindcss -i ./assets/css/input.css -o ./assets/css/style.css

  db:prefetch:
    cmds:
      - "{{.PRISMA_CLIENT}} prefetch"
  db:generate:
    cmds:
      - "{{.PRISMA_CLIENT}} generate"
  db:push:
    cmds:
      - "{{.PRISMA_CLIENT}} db push"