version: 3

dotenv: ['.env']

vars:
  PRISMA_CLIENT: 'go run github.com/steebchen/prisma-client-go db push'

tasks:
  dev:
    cmds:
      - task: db:generate
      - air
  db:generate:
    cmds:
      - "{{.PRISMA_CLIENT}} generate"
  db:push:
    cmds:
      - "{{.PRISMA_CLIENT}} db push"