version: 3

dotenv: ['.env']

vars:
  PRISMA_CLIENT: 'go run github.com/steebchen/prisma-client-go db push'

tasks:
  dev:
    cmds:
      - "{{.PRISMA_CLIENT}} generate"
      - air
  db-push:
    cmds:
      - "{{.PRISMA_CLIENT}} db push"