version: 3

dotenv: ['.env']

vars:
  PRISMA_CLIENT: 'go run github.com/steebchen/prisma-client-go'

tasks:
  dev:
    deps: [db:generate, generate]
    cmds:
      - air
  generate:
    cmds:
      - templ generate
  build:
    deps: [db:generate, test, generate]
    cmds:
      - CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o out .
  test:
    cmds:
      - go test ./... -v          
  upgrade:
    cmds:
      - go get -u ./...

  db:prefetch:
    cmds:
      - "{{.PRISMA_CLIENT}} prefetch"
  db:generate:
    cmds:
      - "{{.PRISMA_CLIENT}} generate"
  db:push:
    cmds:
      - "{{.PRISMA_CLIENT}} db push"