version: 3

dotenv: ['.env']

vars:
  PRISMA_CLIENT: 'go run github.com/steebchen/prisma-client-go'

tasks:
  dev:
    cmds:
      - task: db:generate
      - air
  build:
    cmds:
      - CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o out .
  test:
    cmds:
      - go test ./... -v          

  db:prefetch:
    cmds:
      - "{{.PRISMA_CLIENT}} prefetch"
  db:generate:
    cmds:
      - "{{.PRISMA_CLIENT}} generate"
  db:push:
    cmds:
      - "{{.PRISMA_CLIENT}} db push"