// Code generated by SQLBoiler 4.16.2 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAppConfigurations(t *testing.T) {
	t.Parallel()

	query := AppConfigurations()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAppConfigurationsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AppConfigurations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAppConfigurationsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AppConfigurations().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AppConfigurations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAppConfigurationsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AppConfigurationSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AppConfigurations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAppConfigurationsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AppConfigurationExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AppConfiguration exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AppConfigurationExists to return true, but got false.")
	}
}

func testAppConfigurationsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	appConfigurationFound, err := FindAppConfiguration(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if appConfigurationFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAppConfigurationsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AppConfigurations().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAppConfigurationsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AppConfigurations().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAppConfigurationsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	appConfigurationOne := &AppConfiguration{}
	appConfigurationTwo := &AppConfiguration{}
	if err = randomize.Struct(seed, appConfigurationOne, appConfigurationDBTypes, false, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}
	if err = randomize.Struct(seed, appConfigurationTwo, appConfigurationDBTypes, false, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = appConfigurationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = appConfigurationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AppConfigurations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAppConfigurationsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	appConfigurationOne := &AppConfiguration{}
	appConfigurationTwo := &AppConfiguration{}
	if err = randomize.Struct(seed, appConfigurationOne, appConfigurationDBTypes, false, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}
	if err = randomize.Struct(seed, appConfigurationTwo, appConfigurationDBTypes, false, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = appConfigurationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = appConfigurationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AppConfigurations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func appConfigurationBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *AppConfiguration) error {
	*o = AppConfiguration{}
	return nil
}

func appConfigurationAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *AppConfiguration) error {
	*o = AppConfiguration{}
	return nil
}

func appConfigurationAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *AppConfiguration) error {
	*o = AppConfiguration{}
	return nil
}

func appConfigurationBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AppConfiguration) error {
	*o = AppConfiguration{}
	return nil
}

func appConfigurationAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AppConfiguration) error {
	*o = AppConfiguration{}
	return nil
}

func appConfigurationBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AppConfiguration) error {
	*o = AppConfiguration{}
	return nil
}

func appConfigurationAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AppConfiguration) error {
	*o = AppConfiguration{}
	return nil
}

func appConfigurationBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AppConfiguration) error {
	*o = AppConfiguration{}
	return nil
}

func appConfigurationAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AppConfiguration) error {
	*o = AppConfiguration{}
	return nil
}

func testAppConfigurationsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &AppConfiguration{}
	o := &AppConfiguration{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, false); err != nil {
		t.Errorf("Unable to randomize AppConfiguration object: %s", err)
	}

	AddAppConfigurationHook(boil.BeforeInsertHook, appConfigurationBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	appConfigurationBeforeInsertHooks = []AppConfigurationHook{}

	AddAppConfigurationHook(boil.AfterInsertHook, appConfigurationAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	appConfigurationAfterInsertHooks = []AppConfigurationHook{}

	AddAppConfigurationHook(boil.AfterSelectHook, appConfigurationAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	appConfigurationAfterSelectHooks = []AppConfigurationHook{}

	AddAppConfigurationHook(boil.BeforeUpdateHook, appConfigurationBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	appConfigurationBeforeUpdateHooks = []AppConfigurationHook{}

	AddAppConfigurationHook(boil.AfterUpdateHook, appConfigurationAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	appConfigurationAfterUpdateHooks = []AppConfigurationHook{}

	AddAppConfigurationHook(boil.BeforeDeleteHook, appConfigurationBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	appConfigurationBeforeDeleteHooks = []AppConfigurationHook{}

	AddAppConfigurationHook(boil.AfterDeleteHook, appConfigurationAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	appConfigurationAfterDeleteHooks = []AppConfigurationHook{}

	AddAppConfigurationHook(boil.BeforeUpsertHook, appConfigurationBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	appConfigurationBeforeUpsertHooks = []AppConfigurationHook{}

	AddAppConfigurationHook(boil.AfterUpsertHook, appConfigurationAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	appConfigurationAfterUpsertHooks = []AppConfigurationHook{}
}

func testAppConfigurationsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AppConfigurations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAppConfigurationsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(appConfigurationColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AppConfigurations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAppConfigurationsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAppConfigurationsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AppConfigurationSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAppConfigurationsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AppConfigurations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	appConfigurationDBTypes = map[string]string{`ID`: `TEXT`, `CreatedAt`: `DATE`, `UpdatedAt`: `DATE`, `Version`: `INTEGER`, `Data`: `BLOB`}
	_                       = bytes.MinRead
)

func testAppConfigurationsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(appConfigurationPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(appConfigurationAllColumns) == len(appConfigurationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AppConfigurations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAppConfigurationsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(appConfigurationAllColumns) == len(appConfigurationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AppConfiguration{}
	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AppConfigurations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, appConfigurationDBTypes, true, appConfigurationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(appConfigurationAllColumns, appConfigurationPrimaryKeyColumns) {
		fields = appConfigurationAllColumns
	} else {
		fields = strmangle.SetComplement(
			appConfigurationAllColumns,
			appConfigurationPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AppConfigurationSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAppConfigurationsUpsert(t *testing.T) {
	t.Parallel()
	if len(appConfigurationAllColumns) == len(appConfigurationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AppConfiguration{}
	if err = randomize.Struct(seed, &o, appConfigurationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AppConfiguration: %s", err)
	}

	count, err := AppConfigurations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, appConfigurationDBTypes, false, appConfigurationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AppConfiguration struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AppConfiguration: %s", err)
	}

	count, err = AppConfigurations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
