// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AppConfiguration string
	Channels         string
	Passkeys         string
	Sessions         string
	Settings         string
	Subscriptions    string
	Users            string
	Videos           string
	Views            string
}{
	AppConfiguration: "app_configuration",
	Channels:         "channels",
	Passkeys:         "passkeys",
	Sessions:         "sessions",
	Settings:         "settings",
	Subscriptions:    "subscriptions",
	Users:            "users",
	Videos:           "videos",
	Views:            "views",
}
