// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Channels      string
	Connections   string
	Passkeys      string
	Sessions      string
	Settings      string
	Subscriptions string
	Users         string
	Videos        string
	Views         string
}{
	Channels:      "channels",
	Connections:   "connections",
	Passkeys:      "passkeys",
	Sessions:      "sessions",
	Settings:      "settings",
	Subscriptions: "subscriptions",
	Users:         "users",
	Videos:        "videos",
	Views:         "views",
}
