// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AppConfiguration          string
	Channels                  string
	Passkeys                  string
	PlaylistItems             string
	Playlists                 string
	PodcastEpisodeSegments    string
	PodcastEpisodeTranscripts string
	PodcastProcessingJobs     string
	PodcastSegmentAnalyses    string
	PodcastShows              string
	PodcastSourceValidations  string
	PodcastTranscriptContents string
	PodcastTranscriptionSlots string
	Sessions                  string
	Settings                  string
	Subscriptions             string
	Users                     string
	Videos                    string
	Views                     string
	YoutubeSyncAccounts       string
	YoutubeSyncTargets        string
	YoutubeTVSyncAccounts     string
}{
	AppConfiguration:          "app_configuration",
	Channels:                  "channels",
	Passkeys:                  "passkeys",
	PlaylistItems:             "playlist_items",
	Playlists:                 "playlists",
	PodcastEpisodeSegments:    "podcast_episode_segments",
	PodcastEpisodeTranscripts: "podcast_episode_transcripts",
	PodcastProcessingJobs:     "podcast_processing_jobs",
	PodcastSegmentAnalyses:    "podcast_segment_analyses",
	PodcastShows:              "podcast_shows",
	PodcastSourceValidations:  "podcast_source_validations",
	PodcastTranscriptContents: "podcast_transcript_contents",
	PodcastTranscriptionSlots: "podcast_transcription_slots",
	Sessions:                  "sessions",
	Settings:                  "settings",
	Subscriptions:             "subscriptions",
	Users:                     "users",
	Videos:                    "videos",
	Views:                     "views",
	YoutubeSyncAccounts:       "youtube_sync_accounts",
	YoutubeSyncTargets:        "youtube_sync_targets",
	YoutubeTVSyncAccounts:     "youtube_tv_sync_accounts",
}
