// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PodcastProcessingJob is an object representing the database table.
type PodcastProcessingJob struct {
	ID             string `boil:"id" json:"id" toml:"id" yaml:"id"`
	VideoID        string `boil:"video_id" json:"video_id" toml:"video_id" yaml:"video_id"`
	SourceKey      string `boil:"source_key" json:"source_key" toml:"source_key" yaml:"source_key"`
	Model          string `boil:"model" json:"model" toml:"model" yaml:"model"`
	PromptVersion  string `boil:"prompt_version" json:"prompt_version" toml:"prompt_version" yaml:"prompt_version"`
	Status         string `boil:"status" json:"status" toml:"status" yaml:"status"`
	Phase          string `boil:"phase" json:"phase" toml:"phase" yaml:"phase"`
	Error          string `boil:"error" json:"error" toml:"error" yaml:"error"`
	TranscriptHash string `boil:"transcript_hash" json:"transcript_hash" toml:"transcript_hash" yaml:"transcript_hash"`
	AnalysisID     string `boil:"analysis_id" json:"analysis_id" toml:"analysis_id" yaml:"analysis_id"`
	DurationMS     int64  `boil:"duration_ms" json:"duration_ms" toml:"duration_ms" yaml:"duration_ms"`
	Token          string `boil:"token" json:"token" toml:"token" yaml:"token"`
	LeaseUntilMS   int64  `boil:"lease_until_ms" json:"lease_until_ms" toml:"lease_until_ms" yaml:"lease_until_ms"`
	CreatedAtMS    int64  `boil:"created_at_ms" json:"created_at_ms" toml:"created_at_ms" yaml:"created_at_ms"`
	UpdatedAtMS    int64  `boil:"updated_at_ms" json:"updated_at_ms" toml:"updated_at_ms" yaml:"updated_at_ms"`

	R *podcastProcessingJobR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L podcastProcessingJobL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PodcastProcessingJobColumns = struct {
	ID             string
	VideoID        string
	SourceKey      string
	Model          string
	PromptVersion  string
	Status         string
	Phase          string
	Error          string
	TranscriptHash string
	AnalysisID     string
	DurationMS     string
	Token          string
	LeaseUntilMS   string
	CreatedAtMS    string
	UpdatedAtMS    string
}{
	ID:             "id",
	VideoID:        "video_id",
	SourceKey:      "source_key",
	Model:          "model",
	PromptVersion:  "prompt_version",
	Status:         "status",
	Phase:          "phase",
	Error:          "error",
	TranscriptHash: "transcript_hash",
	AnalysisID:     "analysis_id",
	DurationMS:     "duration_ms",
	Token:          "token",
	LeaseUntilMS:   "lease_until_ms",
	CreatedAtMS:    "created_at_ms",
	UpdatedAtMS:    "updated_at_ms",
}

var PodcastProcessingJobTableColumns = struct {
	ID             string
	VideoID        string
	SourceKey      string
	Model          string
	PromptVersion  string
	Status         string
	Phase          string
	Error          string
	TranscriptHash string
	AnalysisID     string
	DurationMS     string
	Token          string
	LeaseUntilMS   string
	CreatedAtMS    string
	UpdatedAtMS    string
}{
	ID:             "podcast_processing_jobs.id",
	VideoID:        "podcast_processing_jobs.video_id",
	SourceKey:      "podcast_processing_jobs.source_key",
	Model:          "podcast_processing_jobs.model",
	PromptVersion:  "podcast_processing_jobs.prompt_version",
	Status:         "podcast_processing_jobs.status",
	Phase:          "podcast_processing_jobs.phase",
	Error:          "podcast_processing_jobs.error",
	TranscriptHash: "podcast_processing_jobs.transcript_hash",
	AnalysisID:     "podcast_processing_jobs.analysis_id",
	DurationMS:     "podcast_processing_jobs.duration_ms",
	Token:          "podcast_processing_jobs.token",
	LeaseUntilMS:   "podcast_processing_jobs.lease_until_ms",
	CreatedAtMS:    "podcast_processing_jobs.created_at_ms",
	UpdatedAtMS:    "podcast_processing_jobs.updated_at_ms",
}

// Generated where

var PodcastProcessingJobWhere = struct {
	ID             whereHelperstring
	VideoID        whereHelperstring
	SourceKey      whereHelperstring
	Model          whereHelperstring
	PromptVersion  whereHelperstring
	Status         whereHelperstring
	Phase          whereHelperstring
	Error          whereHelperstring
	TranscriptHash whereHelperstring
	AnalysisID     whereHelperstring
	DurationMS     whereHelperint64
	Token          whereHelperstring
	LeaseUntilMS   whereHelperint64
	CreatedAtMS    whereHelperint64
	UpdatedAtMS    whereHelperint64
}{
	ID:             whereHelperstring{field: "\"podcast_processing_jobs\".\"id\""},
	VideoID:        whereHelperstring{field: "\"podcast_processing_jobs\".\"video_id\""},
	SourceKey:      whereHelperstring{field: "\"podcast_processing_jobs\".\"source_key\""},
	Model:          whereHelperstring{field: "\"podcast_processing_jobs\".\"model\""},
	PromptVersion:  whereHelperstring{field: "\"podcast_processing_jobs\".\"prompt_version\""},
	Status:         whereHelperstring{field: "\"podcast_processing_jobs\".\"status\""},
	Phase:          whereHelperstring{field: "\"podcast_processing_jobs\".\"phase\""},
	Error:          whereHelperstring{field: "\"podcast_processing_jobs\".\"error\""},
	TranscriptHash: whereHelperstring{field: "\"podcast_processing_jobs\".\"transcript_hash\""},
	AnalysisID:     whereHelperstring{field: "\"podcast_processing_jobs\".\"analysis_id\""},
	DurationMS:     whereHelperint64{field: "\"podcast_processing_jobs\".\"duration_ms\""},
	Token:          whereHelperstring{field: "\"podcast_processing_jobs\".\"token\""},
	LeaseUntilMS:   whereHelperint64{field: "\"podcast_processing_jobs\".\"lease_until_ms\""},
	CreatedAtMS:    whereHelperint64{field: "\"podcast_processing_jobs\".\"created_at_ms\""},
	UpdatedAtMS:    whereHelperint64{field: "\"podcast_processing_jobs\".\"updated_at_ms\""},
}

// PodcastProcessingJobRels is where relationship names are stored.
var PodcastProcessingJobRels = struct {
	Video string
}{
	Video: "Video",
}

// podcastProcessingJobR is where relationships are stored.
type podcastProcessingJobR struct {
	Video *Video `boil:"Video" json:"Video" toml:"Video" yaml:"Video"`
}

// NewStruct creates a new relationship struct
func (*podcastProcessingJobR) NewStruct() *podcastProcessingJobR {
	return &podcastProcessingJobR{}
}

func (o *PodcastProcessingJob) GetVideo() *Video {
	if o == nil {
		return nil
	}

	return o.R.GetVideo()
}

func (r *podcastProcessingJobR) GetVideo() *Video {
	if r == nil {
		return nil
	}

	return r.Video
}

// podcastProcessingJobL is where Load methods for each relationship are stored.
type podcastProcessingJobL struct{}

var (
	podcastProcessingJobAllColumns            = []string{"id", "video_id", "source_key", "model", "prompt_version", "status", "phase", "error", "transcript_hash", "analysis_id", "duration_ms", "token", "lease_until_ms", "created_at_ms", "updated_at_ms"}
	podcastProcessingJobColumnsWithoutDefault = []string{"id", "video_id", "source_key", "model", "prompt_version", "status", "phase", "error", "transcript_hash", "analysis_id", "duration_ms", "token", "lease_until_ms", "created_at_ms", "updated_at_ms"}
	podcastProcessingJobColumnsWithDefault    = []string{}
	podcastProcessingJobPrimaryKeyColumns     = []string{"id"}
	podcastProcessingJobGeneratedColumns      = []string{}
)

type (
	// PodcastProcessingJobSlice is an alias for a slice of pointers to PodcastProcessingJob.
	// This should almost always be used instead of []PodcastProcessingJob.
	PodcastProcessingJobSlice []*PodcastProcessingJob
	// PodcastProcessingJobHook is the signature for custom PodcastProcessingJob hook methods
	PodcastProcessingJobHook func(context.Context, boil.ContextExecutor, *PodcastProcessingJob) error

	podcastProcessingJobQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	podcastProcessingJobType                 = reflect.TypeOf(&PodcastProcessingJob{})
	podcastProcessingJobMapping              = queries.MakeStructMapping(podcastProcessingJobType)
	podcastProcessingJobPrimaryKeyMapping, _ = queries.BindMapping(podcastProcessingJobType, podcastProcessingJobMapping, podcastProcessingJobPrimaryKeyColumns)
	podcastProcessingJobInsertCacheMut       sync.RWMutex
	podcastProcessingJobInsertCache          = make(map[string]insertCache)
	podcastProcessingJobUpdateCacheMut       sync.RWMutex
	podcastProcessingJobUpdateCache          = make(map[string]updateCache)
	podcastProcessingJobUpsertCacheMut       sync.RWMutex
	podcastProcessingJobUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var podcastProcessingJobAfterSelectMu sync.Mutex
var podcastProcessingJobAfterSelectHooks []PodcastProcessingJobHook

var podcastProcessingJobBeforeInsertMu sync.Mutex
var podcastProcessingJobBeforeInsertHooks []PodcastProcessingJobHook
var podcastProcessingJobAfterInsertMu sync.Mutex
var podcastProcessingJobAfterInsertHooks []PodcastProcessingJobHook

var podcastProcessingJobBeforeUpdateMu sync.Mutex
var podcastProcessingJobBeforeUpdateHooks []PodcastProcessingJobHook
var podcastProcessingJobAfterUpdateMu sync.Mutex
var podcastProcessingJobAfterUpdateHooks []PodcastProcessingJobHook

var podcastProcessingJobBeforeDeleteMu sync.Mutex
var podcastProcessingJobBeforeDeleteHooks []PodcastProcessingJobHook
var podcastProcessingJobAfterDeleteMu sync.Mutex
var podcastProcessingJobAfterDeleteHooks []PodcastProcessingJobHook

var podcastProcessingJobBeforeUpsertMu sync.Mutex
var podcastProcessingJobBeforeUpsertHooks []PodcastProcessingJobHook
var podcastProcessingJobAfterUpsertMu sync.Mutex
var podcastProcessingJobAfterUpsertHooks []PodcastProcessingJobHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PodcastProcessingJob) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastProcessingJobAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PodcastProcessingJob) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastProcessingJobBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PodcastProcessingJob) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastProcessingJobAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PodcastProcessingJob) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastProcessingJobBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PodcastProcessingJob) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastProcessingJobAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PodcastProcessingJob) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastProcessingJobBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PodcastProcessingJob) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastProcessingJobAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PodcastProcessingJob) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastProcessingJobBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PodcastProcessingJob) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastProcessingJobAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPodcastProcessingJobHook registers your hook function for all future operations.
func AddPodcastProcessingJobHook(hookPoint boil.HookPoint, podcastProcessingJobHook PodcastProcessingJobHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		podcastProcessingJobAfterSelectMu.Lock()
		podcastProcessingJobAfterSelectHooks = append(podcastProcessingJobAfterSelectHooks, podcastProcessingJobHook)
		podcastProcessingJobAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		podcastProcessingJobBeforeInsertMu.Lock()
		podcastProcessingJobBeforeInsertHooks = append(podcastProcessingJobBeforeInsertHooks, podcastProcessingJobHook)
		podcastProcessingJobBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		podcastProcessingJobAfterInsertMu.Lock()
		podcastProcessingJobAfterInsertHooks = append(podcastProcessingJobAfterInsertHooks, podcastProcessingJobHook)
		podcastProcessingJobAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		podcastProcessingJobBeforeUpdateMu.Lock()
		podcastProcessingJobBeforeUpdateHooks = append(podcastProcessingJobBeforeUpdateHooks, podcastProcessingJobHook)
		podcastProcessingJobBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		podcastProcessingJobAfterUpdateMu.Lock()
		podcastProcessingJobAfterUpdateHooks = append(podcastProcessingJobAfterUpdateHooks, podcastProcessingJobHook)
		podcastProcessingJobAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		podcastProcessingJobBeforeDeleteMu.Lock()
		podcastProcessingJobBeforeDeleteHooks = append(podcastProcessingJobBeforeDeleteHooks, podcastProcessingJobHook)
		podcastProcessingJobBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		podcastProcessingJobAfterDeleteMu.Lock()
		podcastProcessingJobAfterDeleteHooks = append(podcastProcessingJobAfterDeleteHooks, podcastProcessingJobHook)
		podcastProcessingJobAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		podcastProcessingJobBeforeUpsertMu.Lock()
		podcastProcessingJobBeforeUpsertHooks = append(podcastProcessingJobBeforeUpsertHooks, podcastProcessingJobHook)
		podcastProcessingJobBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		podcastProcessingJobAfterUpsertMu.Lock()
		podcastProcessingJobAfterUpsertHooks = append(podcastProcessingJobAfterUpsertHooks, podcastProcessingJobHook)
		podcastProcessingJobAfterUpsertMu.Unlock()
	}
}

// One returns a single podcastProcessingJob record from the query.
func (q podcastProcessingJobQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PodcastProcessingJob, error) {
	o := &PodcastProcessingJob{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for podcast_processing_jobs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PodcastProcessingJob records from the query.
func (q podcastProcessingJobQuery) All(ctx context.Context, exec boil.ContextExecutor) (PodcastProcessingJobSlice, error) {
	var o []*PodcastProcessingJob

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PodcastProcessingJob slice")
	}

	if len(podcastProcessingJobAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PodcastProcessingJob records in the query.
func (q podcastProcessingJobQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count podcast_processing_jobs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q podcastProcessingJobQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if podcast_processing_jobs exists")
	}

	return count > 0, nil
}

// Video pointed to by the foreign key.
func (o *PodcastProcessingJob) Video(mods ...qm.QueryMod) videoQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.VideoID),
	}

	queryMods = append(queryMods, mods...)

	return Videos(queryMods...)
}

// LoadVideo allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (podcastProcessingJobL) LoadVideo(ctx context.Context, e boil.ContextExecutor, singular bool, maybePodcastProcessingJob interface{}, mods queries.Applicator) error {
	var slice []*PodcastProcessingJob
	var object *PodcastProcessingJob

	if singular {
		var ok bool
		object, ok = maybePodcastProcessingJob.(*PodcastProcessingJob)
		if !ok {
			object = new(PodcastProcessingJob)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePodcastProcessingJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePodcastProcessingJob))
			}
		}
	} else {
		s, ok := maybePodcastProcessingJob.(*[]*PodcastProcessingJob)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePodcastProcessingJob)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePodcastProcessingJob))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &podcastProcessingJobR{}
		}
		args[object.VideoID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &podcastProcessingJobR{}
			}

			args[obj.VideoID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`videos`),
		qm.WhereIn(`videos.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Video")
	}

	var resultSlice []*Video
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Video")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for videos")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for videos")
	}

	if len(videoAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Video = foreign
		if foreign.R == nil {
			foreign.R = &videoR{}
		}
		foreign.R.PodcastProcessingJobs = append(foreign.R.PodcastProcessingJobs, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.VideoID == foreign.ID {
				local.R.Video = foreign
				if foreign.R == nil {
					foreign.R = &videoR{}
				}
				foreign.R.PodcastProcessingJobs = append(foreign.R.PodcastProcessingJobs, local)
				break
			}
		}
	}

	return nil
}

// SetVideo of the podcastProcessingJob to the related item.
// Sets o.R.Video to related.
// Adds o to related.R.PodcastProcessingJobs.
func (o *PodcastProcessingJob) SetVideo(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Video) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"podcast_processing_jobs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"video_id"}),
		strmangle.WhereClause("\"", "\"", 0, podcastProcessingJobPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.VideoID = related.ID
	if o.R == nil {
		o.R = &podcastProcessingJobR{
			Video: related,
		}
	} else {
		o.R.Video = related
	}

	if related.R == nil {
		related.R = &videoR{
			PodcastProcessingJobs: PodcastProcessingJobSlice{o},
		}
	} else {
		related.R.PodcastProcessingJobs = append(related.R.PodcastProcessingJobs, o)
	}

	return nil
}

// PodcastProcessingJobs retrieves all the records using an executor.
func PodcastProcessingJobs(mods ...qm.QueryMod) podcastProcessingJobQuery {
	mods = append(mods, qm.From("\"podcast_processing_jobs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"podcast_processing_jobs\".*"})
	}

	return podcastProcessingJobQuery{q}
}

// FindPodcastProcessingJob retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPodcastProcessingJob(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*PodcastProcessingJob, error) {
	podcastProcessingJobObj := &PodcastProcessingJob{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"podcast_processing_jobs\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, podcastProcessingJobObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from podcast_processing_jobs")
	}

	if err = podcastProcessingJobObj.doAfterSelectHooks(ctx, exec); err != nil {
		return podcastProcessingJobObj, err
	}

	return podcastProcessingJobObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PodcastProcessingJob) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no podcast_processing_jobs provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(podcastProcessingJobColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	podcastProcessingJobInsertCacheMut.RLock()
	cache, cached := podcastProcessingJobInsertCache[key]
	podcastProcessingJobInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			podcastProcessingJobAllColumns,
			podcastProcessingJobColumnsWithDefault,
			podcastProcessingJobColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(podcastProcessingJobType, podcastProcessingJobMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(podcastProcessingJobType, podcastProcessingJobMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"podcast_processing_jobs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"podcast_processing_jobs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into podcast_processing_jobs")
	}

	if !cached {
		podcastProcessingJobInsertCacheMut.Lock()
		podcastProcessingJobInsertCache[key] = cache
		podcastProcessingJobInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PodcastProcessingJob.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PodcastProcessingJob) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	podcastProcessingJobUpdateCacheMut.RLock()
	cache, cached := podcastProcessingJobUpdateCache[key]
	podcastProcessingJobUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			podcastProcessingJobAllColumns,
			podcastProcessingJobPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update podcast_processing_jobs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"podcast_processing_jobs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, podcastProcessingJobPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(podcastProcessingJobType, podcastProcessingJobMapping, append(wl, podcastProcessingJobPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update podcast_processing_jobs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for podcast_processing_jobs")
	}

	if !cached {
		podcastProcessingJobUpdateCacheMut.Lock()
		podcastProcessingJobUpdateCache[key] = cache
		podcastProcessingJobUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q podcastProcessingJobQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for podcast_processing_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for podcast_processing_jobs")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PodcastProcessingJobSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastProcessingJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"podcast_processing_jobs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastProcessingJobPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in podcastProcessingJob slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all podcastProcessingJob")
	}
	return rowsAff, nil
}

// Delete deletes a single PodcastProcessingJob record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PodcastProcessingJob) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PodcastProcessingJob provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), podcastProcessingJobPrimaryKeyMapping)
	sql := "DELETE FROM \"podcast_processing_jobs\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from podcast_processing_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for podcast_processing_jobs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q podcastProcessingJobQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no podcastProcessingJobQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from podcast_processing_jobs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for podcast_processing_jobs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PodcastProcessingJobSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(podcastProcessingJobBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastProcessingJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"podcast_processing_jobs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastProcessingJobPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from podcastProcessingJob slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for podcast_processing_jobs")
	}

	if len(podcastProcessingJobAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PodcastProcessingJob) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPodcastProcessingJob(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PodcastProcessingJobSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PodcastProcessingJobSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastProcessingJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"podcast_processing_jobs\".* FROM \"podcast_processing_jobs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastProcessingJobPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PodcastProcessingJobSlice")
	}

	*o = slice

	return nil
}

// PodcastProcessingJobExists checks if the PodcastProcessingJob row exists.
func PodcastProcessingJobExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"podcast_processing_jobs\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if podcast_processing_jobs exists")
	}

	return exists, nil
}

// Exists checks if the PodcastProcessingJob row exists.
func (o *PodcastProcessingJob) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PodcastProcessingJobExists(ctx, exec, o.ID)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PodcastProcessingJob) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no podcast_processing_jobs provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(podcastProcessingJobColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	podcastProcessingJobUpsertCacheMut.RLock()
	cache, cached := podcastProcessingJobUpsertCache[key]
	podcastProcessingJobUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			podcastProcessingJobAllColumns,
			podcastProcessingJobColumnsWithDefault,
			podcastProcessingJobColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			podcastProcessingJobAllColumns,
			podcastProcessingJobPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert podcast_processing_jobs, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(podcastProcessingJobPrimaryKeyColumns))
			copy(conflict, podcastProcessingJobPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"podcast_processing_jobs\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(podcastProcessingJobType, podcastProcessingJobMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(podcastProcessingJobType, podcastProcessingJobMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert podcast_processing_jobs")
	}

	if !cached {
		podcastProcessingJobUpsertCacheMut.Lock()
		podcastProcessingJobUpsertCache[key] = cache
		podcastProcessingJobUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
