// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PodcastSegmentAnalysis is an object representing the database table.
type PodcastSegmentAnalysis struct {
	ID             string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	VideoID        string      `boil:"video_id" json:"video_id" toml:"video_id" yaml:"video_id"`
	TranscriptHash string      `boil:"transcript_hash" json:"transcript_hash" toml:"transcript_hash" yaml:"transcript_hash"`
	TranscriptURL  string      `boil:"transcript_url" json:"transcript_url" toml:"transcript_url" yaml:"transcript_url"`
	Model          string      `boil:"model" json:"model" toml:"model" yaml:"model"`
	PromptVersion  string      `boil:"prompt_version" json:"prompt_version" toml:"prompt_version" yaml:"prompt_version"`
	Status         string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	Error          null.String `boil:"error" json:"error,omitempty" toml:"error" yaml:"error,omitempty"`
	StartedAt      null.Time   `boil:"started_at" json:"started_at,omitempty" toml:"started_at" yaml:"started_at,omitempty"`
	CompletedAt    null.Time   `boil:"completed_at" json:"completed_at,omitempty" toml:"completed_at" yaml:"completed_at,omitempty"`
	CreatedAt      time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *podcastSegmentAnalysisR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L podcastSegmentAnalysisL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PodcastSegmentAnalysisColumns = struct {
	ID             string
	VideoID        string
	TranscriptHash string
	TranscriptURL  string
	Model          string
	PromptVersion  string
	Status         string
	Error          string
	StartedAt      string
	CompletedAt    string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "id",
	VideoID:        "video_id",
	TranscriptHash: "transcript_hash",
	TranscriptURL:  "transcript_url",
	Model:          "model",
	PromptVersion:  "prompt_version",
	Status:         "status",
	Error:          "error",
	StartedAt:      "started_at",
	CompletedAt:    "completed_at",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var PodcastSegmentAnalysisTableColumns = struct {
	ID             string
	VideoID        string
	TranscriptHash string
	TranscriptURL  string
	Model          string
	PromptVersion  string
	Status         string
	Error          string
	StartedAt      string
	CompletedAt    string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "podcast_segment_analyses.id",
	VideoID:        "podcast_segment_analyses.video_id",
	TranscriptHash: "podcast_segment_analyses.transcript_hash",
	TranscriptURL:  "podcast_segment_analyses.transcript_url",
	Model:          "podcast_segment_analyses.model",
	PromptVersion:  "podcast_segment_analyses.prompt_version",
	Status:         "podcast_segment_analyses.status",
	Error:          "podcast_segment_analyses.error",
	StartedAt:      "podcast_segment_analyses.started_at",
	CompletedAt:    "podcast_segment_analyses.completed_at",
	CreatedAt:      "podcast_segment_analyses.created_at",
	UpdatedAt:      "podcast_segment_analyses.updated_at",
}

// Generated where

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var PodcastSegmentAnalysisWhere = struct {
	ID             whereHelperstring
	VideoID        whereHelperstring
	TranscriptHash whereHelperstring
	TranscriptURL  whereHelperstring
	Model          whereHelperstring
	PromptVersion  whereHelperstring
	Status         whereHelperstring
	Error          whereHelpernull_String
	StartedAt      whereHelpernull_Time
	CompletedAt    whereHelpernull_Time
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	ID:             whereHelperstring{field: "\"podcast_segment_analyses\".\"id\""},
	VideoID:        whereHelperstring{field: "\"podcast_segment_analyses\".\"video_id\""},
	TranscriptHash: whereHelperstring{field: "\"podcast_segment_analyses\".\"transcript_hash\""},
	TranscriptURL:  whereHelperstring{field: "\"podcast_segment_analyses\".\"transcript_url\""},
	Model:          whereHelperstring{field: "\"podcast_segment_analyses\".\"model\""},
	PromptVersion:  whereHelperstring{field: "\"podcast_segment_analyses\".\"prompt_version\""},
	Status:         whereHelperstring{field: "\"podcast_segment_analyses\".\"status\""},
	Error:          whereHelpernull_String{field: "\"podcast_segment_analyses\".\"error\""},
	StartedAt:      whereHelpernull_Time{field: "\"podcast_segment_analyses\".\"started_at\""},
	CompletedAt:    whereHelpernull_Time{field: "\"podcast_segment_analyses\".\"completed_at\""},
	CreatedAt:      whereHelpertime_Time{field: "\"podcast_segment_analyses\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"podcast_segment_analyses\".\"updated_at\""},
}

// PodcastSegmentAnalysisRels is where relationship names are stored.
var PodcastSegmentAnalysisRels = struct {
	Video                          string
	AnalysisPodcastEpisodeSegments string
}{
	Video:                          "Video",
	AnalysisPodcastEpisodeSegments: "AnalysisPodcastEpisodeSegments",
}

// podcastSegmentAnalysisR is where relationships are stored.
type podcastSegmentAnalysisR struct {
	Video                          *Video                     `boil:"Video" json:"Video" toml:"Video" yaml:"Video"`
	AnalysisPodcastEpisodeSegments PodcastEpisodeSegmentSlice `boil:"AnalysisPodcastEpisodeSegments" json:"AnalysisPodcastEpisodeSegments" toml:"AnalysisPodcastEpisodeSegments" yaml:"AnalysisPodcastEpisodeSegments"`
}

// NewStruct creates a new relationship struct
func (*podcastSegmentAnalysisR) NewStruct() *podcastSegmentAnalysisR {
	return &podcastSegmentAnalysisR{}
}

func (o *PodcastSegmentAnalysis) GetVideo() *Video {
	if o == nil {
		return nil
	}

	return o.R.GetVideo()
}

func (r *podcastSegmentAnalysisR) GetVideo() *Video {
	if r == nil {
		return nil
	}

	return r.Video
}

func (o *PodcastSegmentAnalysis) GetAnalysisPodcastEpisodeSegments() PodcastEpisodeSegmentSlice {
	if o == nil {
		return nil
	}

	return o.R.GetAnalysisPodcastEpisodeSegments()
}

func (r *podcastSegmentAnalysisR) GetAnalysisPodcastEpisodeSegments() PodcastEpisodeSegmentSlice {
	if r == nil {
		return nil
	}

	return r.AnalysisPodcastEpisodeSegments
}

// podcastSegmentAnalysisL is where Load methods for each relationship are stored.
type podcastSegmentAnalysisL struct{}

var (
	podcastSegmentAnalysisAllColumns            = []string{"id", "video_id", "transcript_hash", "transcript_url", "model", "prompt_version", "status", "error", "started_at", "completed_at", "created_at", "updated_at"}
	podcastSegmentAnalysisColumnsWithoutDefault = []string{"id", "video_id", "transcript_hash", "transcript_url", "model", "prompt_version", "status", "error", "started_at", "completed_at", "created_at", "updated_at"}
	podcastSegmentAnalysisColumnsWithDefault    = []string{}
	podcastSegmentAnalysisPrimaryKeyColumns     = []string{"id"}
	podcastSegmentAnalysisGeneratedColumns      = []string{}
)

type (
	// PodcastSegmentAnalysisSlice is an alias for a slice of pointers to PodcastSegmentAnalysis.
	// This should almost always be used instead of []PodcastSegmentAnalysis.
	PodcastSegmentAnalysisSlice []*PodcastSegmentAnalysis
	// PodcastSegmentAnalysisHook is the signature for custom PodcastSegmentAnalysis hook methods
	PodcastSegmentAnalysisHook func(context.Context, boil.ContextExecutor, *PodcastSegmentAnalysis) error

	podcastSegmentAnalysisQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	podcastSegmentAnalysisType                 = reflect.TypeOf(&PodcastSegmentAnalysis{})
	podcastSegmentAnalysisMapping              = queries.MakeStructMapping(podcastSegmentAnalysisType)
	podcastSegmentAnalysisPrimaryKeyMapping, _ = queries.BindMapping(podcastSegmentAnalysisType, podcastSegmentAnalysisMapping, podcastSegmentAnalysisPrimaryKeyColumns)
	podcastSegmentAnalysisInsertCacheMut       sync.RWMutex
	podcastSegmentAnalysisInsertCache          = make(map[string]insertCache)
	podcastSegmentAnalysisUpdateCacheMut       sync.RWMutex
	podcastSegmentAnalysisUpdateCache          = make(map[string]updateCache)
	podcastSegmentAnalysisUpsertCacheMut       sync.RWMutex
	podcastSegmentAnalysisUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var podcastSegmentAnalysisAfterSelectMu sync.Mutex
var podcastSegmentAnalysisAfterSelectHooks []PodcastSegmentAnalysisHook

var podcastSegmentAnalysisBeforeInsertMu sync.Mutex
var podcastSegmentAnalysisBeforeInsertHooks []PodcastSegmentAnalysisHook
var podcastSegmentAnalysisAfterInsertMu sync.Mutex
var podcastSegmentAnalysisAfterInsertHooks []PodcastSegmentAnalysisHook

var podcastSegmentAnalysisBeforeUpdateMu sync.Mutex
var podcastSegmentAnalysisBeforeUpdateHooks []PodcastSegmentAnalysisHook
var podcastSegmentAnalysisAfterUpdateMu sync.Mutex
var podcastSegmentAnalysisAfterUpdateHooks []PodcastSegmentAnalysisHook

var podcastSegmentAnalysisBeforeDeleteMu sync.Mutex
var podcastSegmentAnalysisBeforeDeleteHooks []PodcastSegmentAnalysisHook
var podcastSegmentAnalysisAfterDeleteMu sync.Mutex
var podcastSegmentAnalysisAfterDeleteHooks []PodcastSegmentAnalysisHook

var podcastSegmentAnalysisBeforeUpsertMu sync.Mutex
var podcastSegmentAnalysisBeforeUpsertHooks []PodcastSegmentAnalysisHook
var podcastSegmentAnalysisAfterUpsertMu sync.Mutex
var podcastSegmentAnalysisAfterUpsertHooks []PodcastSegmentAnalysisHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PodcastSegmentAnalysis) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastSegmentAnalysisAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PodcastSegmentAnalysis) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastSegmentAnalysisBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PodcastSegmentAnalysis) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastSegmentAnalysisAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PodcastSegmentAnalysis) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastSegmentAnalysisBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PodcastSegmentAnalysis) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastSegmentAnalysisAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PodcastSegmentAnalysis) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastSegmentAnalysisBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PodcastSegmentAnalysis) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastSegmentAnalysisAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PodcastSegmentAnalysis) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastSegmentAnalysisBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PodcastSegmentAnalysis) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastSegmentAnalysisAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPodcastSegmentAnalysisHook registers your hook function for all future operations.
func AddPodcastSegmentAnalysisHook(hookPoint boil.HookPoint, podcastSegmentAnalysisHook PodcastSegmentAnalysisHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		podcastSegmentAnalysisAfterSelectMu.Lock()
		podcastSegmentAnalysisAfterSelectHooks = append(podcastSegmentAnalysisAfterSelectHooks, podcastSegmentAnalysisHook)
		podcastSegmentAnalysisAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		podcastSegmentAnalysisBeforeInsertMu.Lock()
		podcastSegmentAnalysisBeforeInsertHooks = append(podcastSegmentAnalysisBeforeInsertHooks, podcastSegmentAnalysisHook)
		podcastSegmentAnalysisBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		podcastSegmentAnalysisAfterInsertMu.Lock()
		podcastSegmentAnalysisAfterInsertHooks = append(podcastSegmentAnalysisAfterInsertHooks, podcastSegmentAnalysisHook)
		podcastSegmentAnalysisAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		podcastSegmentAnalysisBeforeUpdateMu.Lock()
		podcastSegmentAnalysisBeforeUpdateHooks = append(podcastSegmentAnalysisBeforeUpdateHooks, podcastSegmentAnalysisHook)
		podcastSegmentAnalysisBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		podcastSegmentAnalysisAfterUpdateMu.Lock()
		podcastSegmentAnalysisAfterUpdateHooks = append(podcastSegmentAnalysisAfterUpdateHooks, podcastSegmentAnalysisHook)
		podcastSegmentAnalysisAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		podcastSegmentAnalysisBeforeDeleteMu.Lock()
		podcastSegmentAnalysisBeforeDeleteHooks = append(podcastSegmentAnalysisBeforeDeleteHooks, podcastSegmentAnalysisHook)
		podcastSegmentAnalysisBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		podcastSegmentAnalysisAfterDeleteMu.Lock()
		podcastSegmentAnalysisAfterDeleteHooks = append(podcastSegmentAnalysisAfterDeleteHooks, podcastSegmentAnalysisHook)
		podcastSegmentAnalysisAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		podcastSegmentAnalysisBeforeUpsertMu.Lock()
		podcastSegmentAnalysisBeforeUpsertHooks = append(podcastSegmentAnalysisBeforeUpsertHooks, podcastSegmentAnalysisHook)
		podcastSegmentAnalysisBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		podcastSegmentAnalysisAfterUpsertMu.Lock()
		podcastSegmentAnalysisAfterUpsertHooks = append(podcastSegmentAnalysisAfterUpsertHooks, podcastSegmentAnalysisHook)
		podcastSegmentAnalysisAfterUpsertMu.Unlock()
	}
}

// One returns a single podcastSegmentAnalysis record from the query.
func (q podcastSegmentAnalysisQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PodcastSegmentAnalysis, error) {
	o := &PodcastSegmentAnalysis{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for podcast_segment_analyses")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PodcastSegmentAnalysis records from the query.
func (q podcastSegmentAnalysisQuery) All(ctx context.Context, exec boil.ContextExecutor) (PodcastSegmentAnalysisSlice, error) {
	var o []*PodcastSegmentAnalysis

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PodcastSegmentAnalysis slice")
	}

	if len(podcastSegmentAnalysisAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PodcastSegmentAnalysis records in the query.
func (q podcastSegmentAnalysisQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count podcast_segment_analyses rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q podcastSegmentAnalysisQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if podcast_segment_analyses exists")
	}

	return count > 0, nil
}

// Video pointed to by the foreign key.
func (o *PodcastSegmentAnalysis) Video(mods ...qm.QueryMod) videoQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.VideoID),
	}

	queryMods = append(queryMods, mods...)

	return Videos(queryMods...)
}

// AnalysisPodcastEpisodeSegments retrieves all the podcast_episode_segment's PodcastEpisodeSegments with an executor via analysis_id column.
func (o *PodcastSegmentAnalysis) AnalysisPodcastEpisodeSegments(mods ...qm.QueryMod) podcastEpisodeSegmentQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"podcast_episode_segments\".\"analysis_id\"=?", o.ID),
	)

	return PodcastEpisodeSegments(queryMods...)
}

// LoadVideo allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (podcastSegmentAnalysisL) LoadVideo(ctx context.Context, e boil.ContextExecutor, singular bool, maybePodcastSegmentAnalysis interface{}, mods queries.Applicator) error {
	var slice []*PodcastSegmentAnalysis
	var object *PodcastSegmentAnalysis

	if singular {
		var ok bool
		object, ok = maybePodcastSegmentAnalysis.(*PodcastSegmentAnalysis)
		if !ok {
			object = new(PodcastSegmentAnalysis)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePodcastSegmentAnalysis)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePodcastSegmentAnalysis))
			}
		}
	} else {
		s, ok := maybePodcastSegmentAnalysis.(*[]*PodcastSegmentAnalysis)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePodcastSegmentAnalysis)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePodcastSegmentAnalysis))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &podcastSegmentAnalysisR{}
		}
		args[object.VideoID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &podcastSegmentAnalysisR{}
			}

			args[obj.VideoID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`videos`),
		qm.WhereIn(`videos.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Video")
	}

	var resultSlice []*Video
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Video")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for videos")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for videos")
	}

	if len(videoAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Video = foreign
		if foreign.R == nil {
			foreign.R = &videoR{}
		}
		foreign.R.PodcastSegmentAnalyses = append(foreign.R.PodcastSegmentAnalyses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.VideoID == foreign.ID {
				local.R.Video = foreign
				if foreign.R == nil {
					foreign.R = &videoR{}
				}
				foreign.R.PodcastSegmentAnalyses = append(foreign.R.PodcastSegmentAnalyses, local)
				break
			}
		}
	}

	return nil
}

// LoadAnalysisPodcastEpisodeSegments allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (podcastSegmentAnalysisL) LoadAnalysisPodcastEpisodeSegments(ctx context.Context, e boil.ContextExecutor, singular bool, maybePodcastSegmentAnalysis interface{}, mods queries.Applicator) error {
	var slice []*PodcastSegmentAnalysis
	var object *PodcastSegmentAnalysis

	if singular {
		var ok bool
		object, ok = maybePodcastSegmentAnalysis.(*PodcastSegmentAnalysis)
		if !ok {
			object = new(PodcastSegmentAnalysis)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePodcastSegmentAnalysis)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePodcastSegmentAnalysis))
			}
		}
	} else {
		s, ok := maybePodcastSegmentAnalysis.(*[]*PodcastSegmentAnalysis)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePodcastSegmentAnalysis)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePodcastSegmentAnalysis))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &podcastSegmentAnalysisR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &podcastSegmentAnalysisR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`podcast_episode_segments`),
		qm.WhereIn(`podcast_episode_segments.analysis_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load podcast_episode_segments")
	}

	var resultSlice []*PodcastEpisodeSegment
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice podcast_episode_segments")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on podcast_episode_segments")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for podcast_episode_segments")
	}

	if len(podcastEpisodeSegmentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.AnalysisPodcastEpisodeSegments = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &podcastEpisodeSegmentR{}
			}
			foreign.R.Analysis = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.AnalysisID) {
				local.R.AnalysisPodcastEpisodeSegments = append(local.R.AnalysisPodcastEpisodeSegments, foreign)
				if foreign.R == nil {
					foreign.R = &podcastEpisodeSegmentR{}
				}
				foreign.R.Analysis = local
				break
			}
		}
	}

	return nil
}

// SetVideo of the podcastSegmentAnalysis to the related item.
// Sets o.R.Video to related.
// Adds o to related.R.PodcastSegmentAnalyses.
func (o *PodcastSegmentAnalysis) SetVideo(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Video) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"podcast_segment_analyses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"video_id"}),
		strmangle.WhereClause("\"", "\"", 0, podcastSegmentAnalysisPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.VideoID = related.ID
	if o.R == nil {
		o.R = &podcastSegmentAnalysisR{
			Video: related,
		}
	} else {
		o.R.Video = related
	}

	if related.R == nil {
		related.R = &videoR{
			PodcastSegmentAnalyses: PodcastSegmentAnalysisSlice{o},
		}
	} else {
		related.R.PodcastSegmentAnalyses = append(related.R.PodcastSegmentAnalyses, o)
	}

	return nil
}

// AddAnalysisPodcastEpisodeSegments adds the given related objects to the existing relationships
// of the podcast_segment_analysis, optionally inserting them as new records.
// Appends related to o.R.AnalysisPodcastEpisodeSegments.
// Sets related.R.Analysis appropriately.
func (o *PodcastSegmentAnalysis) AddAnalysisPodcastEpisodeSegments(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PodcastEpisodeSegment) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.AnalysisID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"podcast_episode_segments\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 0, []string{"analysis_id"}),
				strmangle.WhereClause("\"", "\"", 0, podcastEpisodeSegmentPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.AnalysisID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &podcastSegmentAnalysisR{
			AnalysisPodcastEpisodeSegments: related,
		}
	} else {
		o.R.AnalysisPodcastEpisodeSegments = append(o.R.AnalysisPodcastEpisodeSegments, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &podcastEpisodeSegmentR{
				Analysis: o,
			}
		} else {
			rel.R.Analysis = o
		}
	}
	return nil
}

// SetAnalysisPodcastEpisodeSegments removes all previously related items of the
// podcast_segment_analysis replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Analysis's AnalysisPodcastEpisodeSegments accordingly.
// Replaces o.R.AnalysisPodcastEpisodeSegments with related.
// Sets related.R.Analysis's AnalysisPodcastEpisodeSegments accordingly.
func (o *PodcastSegmentAnalysis) SetAnalysisPodcastEpisodeSegments(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PodcastEpisodeSegment) error {
	query := "update \"podcast_episode_segments\" set \"analysis_id\" = null where \"analysis_id\" = ?"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.AnalysisPodcastEpisodeSegments {
			queries.SetScanner(&rel.AnalysisID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Analysis = nil
		}
		o.R.AnalysisPodcastEpisodeSegments = nil
	}

	return o.AddAnalysisPodcastEpisodeSegments(ctx, exec, insert, related...)
}

// RemoveAnalysisPodcastEpisodeSegments relationships from objects passed in.
// Removes related items from R.AnalysisPodcastEpisodeSegments (uses pointer comparison, removal does not keep order)
// Sets related.R.Analysis.
func (o *PodcastSegmentAnalysis) RemoveAnalysisPodcastEpisodeSegments(ctx context.Context, exec boil.ContextExecutor, related ...*PodcastEpisodeSegment) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.AnalysisID, nil)
		if rel.R != nil {
			rel.R.Analysis = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("analysis_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.AnalysisPodcastEpisodeSegments {
			if rel != ri {
				continue
			}

			ln := len(o.R.AnalysisPodcastEpisodeSegments)
			if ln > 1 && i < ln-1 {
				o.R.AnalysisPodcastEpisodeSegments[i] = o.R.AnalysisPodcastEpisodeSegments[ln-1]
			}
			o.R.AnalysisPodcastEpisodeSegments = o.R.AnalysisPodcastEpisodeSegments[:ln-1]
			break
		}
	}

	return nil
}

// PodcastSegmentAnalyses retrieves all the records using an executor.
func PodcastSegmentAnalyses(mods ...qm.QueryMod) podcastSegmentAnalysisQuery {
	mods = append(mods, qm.From("\"podcast_segment_analyses\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"podcast_segment_analyses\".*"})
	}

	return podcastSegmentAnalysisQuery{q}
}

// FindPodcastSegmentAnalysis retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPodcastSegmentAnalysis(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*PodcastSegmentAnalysis, error) {
	podcastSegmentAnalysisObj := &PodcastSegmentAnalysis{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"podcast_segment_analyses\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, podcastSegmentAnalysisObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from podcast_segment_analyses")
	}

	if err = podcastSegmentAnalysisObj.doAfterSelectHooks(ctx, exec); err != nil {
		return podcastSegmentAnalysisObj, err
	}

	return podcastSegmentAnalysisObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PodcastSegmentAnalysis) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no podcast_segment_analyses provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(podcastSegmentAnalysisColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	podcastSegmentAnalysisInsertCacheMut.RLock()
	cache, cached := podcastSegmentAnalysisInsertCache[key]
	podcastSegmentAnalysisInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			podcastSegmentAnalysisAllColumns,
			podcastSegmentAnalysisColumnsWithDefault,
			podcastSegmentAnalysisColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(podcastSegmentAnalysisType, podcastSegmentAnalysisMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(podcastSegmentAnalysisType, podcastSegmentAnalysisMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"podcast_segment_analyses\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"podcast_segment_analyses\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into podcast_segment_analyses")
	}

	if !cached {
		podcastSegmentAnalysisInsertCacheMut.Lock()
		podcastSegmentAnalysisInsertCache[key] = cache
		podcastSegmentAnalysisInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PodcastSegmentAnalysis.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PodcastSegmentAnalysis) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	podcastSegmentAnalysisUpdateCacheMut.RLock()
	cache, cached := podcastSegmentAnalysisUpdateCache[key]
	podcastSegmentAnalysisUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			podcastSegmentAnalysisAllColumns,
			podcastSegmentAnalysisPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update podcast_segment_analyses, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"podcast_segment_analyses\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, podcastSegmentAnalysisPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(podcastSegmentAnalysisType, podcastSegmentAnalysisMapping, append(wl, podcastSegmentAnalysisPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update podcast_segment_analyses row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for podcast_segment_analyses")
	}

	if !cached {
		podcastSegmentAnalysisUpdateCacheMut.Lock()
		podcastSegmentAnalysisUpdateCache[key] = cache
		podcastSegmentAnalysisUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q podcastSegmentAnalysisQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for podcast_segment_analyses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for podcast_segment_analyses")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PodcastSegmentAnalysisSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastSegmentAnalysisPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"podcast_segment_analyses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastSegmentAnalysisPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in podcastSegmentAnalysis slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all podcastSegmentAnalysis")
	}
	return rowsAff, nil
}

// Delete deletes a single PodcastSegmentAnalysis record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PodcastSegmentAnalysis) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PodcastSegmentAnalysis provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), podcastSegmentAnalysisPrimaryKeyMapping)
	sql := "DELETE FROM \"podcast_segment_analyses\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from podcast_segment_analyses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for podcast_segment_analyses")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q podcastSegmentAnalysisQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no podcastSegmentAnalysisQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from podcast_segment_analyses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for podcast_segment_analyses")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PodcastSegmentAnalysisSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(podcastSegmentAnalysisBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastSegmentAnalysisPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"podcast_segment_analyses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastSegmentAnalysisPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from podcastSegmentAnalysis slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for podcast_segment_analyses")
	}

	if len(podcastSegmentAnalysisAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PodcastSegmentAnalysis) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPodcastSegmentAnalysis(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PodcastSegmentAnalysisSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PodcastSegmentAnalysisSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastSegmentAnalysisPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"podcast_segment_analyses\".* FROM \"podcast_segment_analyses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastSegmentAnalysisPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PodcastSegmentAnalysisSlice")
	}

	*o = slice

	return nil
}

// PodcastSegmentAnalysisExists checks if the PodcastSegmentAnalysis row exists.
func PodcastSegmentAnalysisExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"podcast_segment_analyses\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if podcast_segment_analyses exists")
	}

	return exists, nil
}

// Exists checks if the PodcastSegmentAnalysis row exists.
func (o *PodcastSegmentAnalysis) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PodcastSegmentAnalysisExists(ctx, exec, o.ID)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PodcastSegmentAnalysis) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no podcast_segment_analyses provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(podcastSegmentAnalysisColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	podcastSegmentAnalysisUpsertCacheMut.RLock()
	cache, cached := podcastSegmentAnalysisUpsertCache[key]
	podcastSegmentAnalysisUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			podcastSegmentAnalysisAllColumns,
			podcastSegmentAnalysisColumnsWithDefault,
			podcastSegmentAnalysisColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			podcastSegmentAnalysisAllColumns,
			podcastSegmentAnalysisPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert podcast_segment_analyses, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(podcastSegmentAnalysisPrimaryKeyColumns))
			copy(conflict, podcastSegmentAnalysisPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"podcast_segment_analyses\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(podcastSegmentAnalysisType, podcastSegmentAnalysisMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(podcastSegmentAnalysisType, podcastSegmentAnalysisMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert podcast_segment_analyses")
	}

	if !cached {
		podcastSegmentAnalysisUpsertCacheMut.Lock()
		podcastSegmentAnalysisUpsertCache[key] = cache
		podcastSegmentAnalysisUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
