// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PodcastShow is an object representing the database table.
type PodcastShow struct {
	ChannelID    string      `boil:"channel_id" json:"channel_id" toml:"channel_id" yaml:"channel_id"`
	CreatedAt    time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	FeedURL      string      `boil:"feed_url" json:"feed_url" toml:"feed_url" yaml:"feed_url"`
	Etag         null.String `boil:"etag" json:"etag,omitempty" toml:"etag" yaml:"etag,omitempty"`
	LastModified null.String `boil:"last_modified" json:"last_modified,omitempty" toml:"last_modified" yaml:"last_modified,omitempty"`

	R *podcastShowR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L podcastShowL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PodcastShowColumns = struct {
	ChannelID    string
	CreatedAt    string
	UpdatedAt    string
	FeedURL      string
	Etag         string
	LastModified string
}{
	ChannelID:    "channel_id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	FeedURL:      "feed_url",
	Etag:         "etag",
	LastModified: "last_modified",
}

var PodcastShowTableColumns = struct {
	ChannelID    string
	CreatedAt    string
	UpdatedAt    string
	FeedURL      string
	Etag         string
	LastModified string
}{
	ChannelID:    "podcast_shows.channel_id",
	CreatedAt:    "podcast_shows.created_at",
	UpdatedAt:    "podcast_shows.updated_at",
	FeedURL:      "podcast_shows.feed_url",
	Etag:         "podcast_shows.etag",
	LastModified: "podcast_shows.last_modified",
}

// Generated where

var PodcastShowWhere = struct {
	ChannelID    whereHelperstring
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
	FeedURL      whereHelperstring
	Etag         whereHelpernull_String
	LastModified whereHelpernull_String
}{
	ChannelID:    whereHelperstring{field: "\"podcast_shows\".\"channel_id\""},
	CreatedAt:    whereHelpertime_Time{field: "\"podcast_shows\".\"created_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"podcast_shows\".\"updated_at\""},
	FeedURL:      whereHelperstring{field: "\"podcast_shows\".\"feed_url\""},
	Etag:         whereHelpernull_String{field: "\"podcast_shows\".\"etag\""},
	LastModified: whereHelpernull_String{field: "\"podcast_shows\".\"last_modified\""},
}

// PodcastShowRels is where relationship names are stored.
var PodcastShowRels = struct {
	Channel string
}{
	Channel: "Channel",
}

// podcastShowR is where relationships are stored.
type podcastShowR struct {
	Channel *Channel `boil:"Channel" json:"Channel" toml:"Channel" yaml:"Channel"`
}

// NewStruct creates a new relationship struct
func (*podcastShowR) NewStruct() *podcastShowR {
	return &podcastShowR{}
}

func (o *PodcastShow) GetChannel() *Channel {
	if o == nil {
		return nil
	}

	return o.R.GetChannel()
}

func (r *podcastShowR) GetChannel() *Channel {
	if r == nil {
		return nil
	}

	return r.Channel
}

// podcastShowL is where Load methods for each relationship are stored.
type podcastShowL struct{}

var (
	podcastShowAllColumns            = []string{"channel_id", "created_at", "updated_at", "feed_url", "etag", "last_modified"}
	podcastShowColumnsWithoutDefault = []string{"channel_id", "created_at", "updated_at", "feed_url", "etag", "last_modified"}
	podcastShowColumnsWithDefault    = []string{}
	podcastShowPrimaryKeyColumns     = []string{"channel_id"}
	podcastShowGeneratedColumns      = []string{}
)

type (
	// PodcastShowSlice is an alias for a slice of pointers to PodcastShow.
	// This should almost always be used instead of []PodcastShow.
	PodcastShowSlice []*PodcastShow
	// PodcastShowHook is the signature for custom PodcastShow hook methods
	PodcastShowHook func(context.Context, boil.ContextExecutor, *PodcastShow) error

	podcastShowQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	podcastShowType                 = reflect.TypeOf(&PodcastShow{})
	podcastShowMapping              = queries.MakeStructMapping(podcastShowType)
	podcastShowPrimaryKeyMapping, _ = queries.BindMapping(podcastShowType, podcastShowMapping, podcastShowPrimaryKeyColumns)
	podcastShowInsertCacheMut       sync.RWMutex
	podcastShowInsertCache          = make(map[string]insertCache)
	podcastShowUpdateCacheMut       sync.RWMutex
	podcastShowUpdateCache          = make(map[string]updateCache)
	podcastShowUpsertCacheMut       sync.RWMutex
	podcastShowUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var podcastShowAfterSelectMu sync.Mutex
var podcastShowAfterSelectHooks []PodcastShowHook

var podcastShowBeforeInsertMu sync.Mutex
var podcastShowBeforeInsertHooks []PodcastShowHook
var podcastShowAfterInsertMu sync.Mutex
var podcastShowAfterInsertHooks []PodcastShowHook

var podcastShowBeforeUpdateMu sync.Mutex
var podcastShowBeforeUpdateHooks []PodcastShowHook
var podcastShowAfterUpdateMu sync.Mutex
var podcastShowAfterUpdateHooks []PodcastShowHook

var podcastShowBeforeDeleteMu sync.Mutex
var podcastShowBeforeDeleteHooks []PodcastShowHook
var podcastShowAfterDeleteMu sync.Mutex
var podcastShowAfterDeleteHooks []PodcastShowHook

var podcastShowBeforeUpsertMu sync.Mutex
var podcastShowBeforeUpsertHooks []PodcastShowHook
var podcastShowAfterUpsertMu sync.Mutex
var podcastShowAfterUpsertHooks []PodcastShowHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PodcastShow) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastShowAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PodcastShow) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastShowBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PodcastShow) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastShowAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PodcastShow) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastShowBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PodcastShow) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastShowAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PodcastShow) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastShowBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PodcastShow) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastShowAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PodcastShow) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastShowBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PodcastShow) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastShowAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPodcastShowHook registers your hook function for all future operations.
func AddPodcastShowHook(hookPoint boil.HookPoint, podcastShowHook PodcastShowHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		podcastShowAfterSelectMu.Lock()
		podcastShowAfterSelectHooks = append(podcastShowAfterSelectHooks, podcastShowHook)
		podcastShowAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		podcastShowBeforeInsertMu.Lock()
		podcastShowBeforeInsertHooks = append(podcastShowBeforeInsertHooks, podcastShowHook)
		podcastShowBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		podcastShowAfterInsertMu.Lock()
		podcastShowAfterInsertHooks = append(podcastShowAfterInsertHooks, podcastShowHook)
		podcastShowAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		podcastShowBeforeUpdateMu.Lock()
		podcastShowBeforeUpdateHooks = append(podcastShowBeforeUpdateHooks, podcastShowHook)
		podcastShowBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		podcastShowAfterUpdateMu.Lock()
		podcastShowAfterUpdateHooks = append(podcastShowAfterUpdateHooks, podcastShowHook)
		podcastShowAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		podcastShowBeforeDeleteMu.Lock()
		podcastShowBeforeDeleteHooks = append(podcastShowBeforeDeleteHooks, podcastShowHook)
		podcastShowBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		podcastShowAfterDeleteMu.Lock()
		podcastShowAfterDeleteHooks = append(podcastShowAfterDeleteHooks, podcastShowHook)
		podcastShowAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		podcastShowBeforeUpsertMu.Lock()
		podcastShowBeforeUpsertHooks = append(podcastShowBeforeUpsertHooks, podcastShowHook)
		podcastShowBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		podcastShowAfterUpsertMu.Lock()
		podcastShowAfterUpsertHooks = append(podcastShowAfterUpsertHooks, podcastShowHook)
		podcastShowAfterUpsertMu.Unlock()
	}
}

// One returns a single podcastShow record from the query.
func (q podcastShowQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PodcastShow, error) {
	o := &PodcastShow{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for podcast_shows")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PodcastShow records from the query.
func (q podcastShowQuery) All(ctx context.Context, exec boil.ContextExecutor) (PodcastShowSlice, error) {
	var o []*PodcastShow

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PodcastShow slice")
	}

	if len(podcastShowAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PodcastShow records in the query.
func (q podcastShowQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count podcast_shows rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q podcastShowQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if podcast_shows exists")
	}

	return count > 0, nil
}

// Channel pointed to by the foreign key.
func (o *PodcastShow) Channel(mods ...qm.QueryMod) channelQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ChannelID),
	}

	queryMods = append(queryMods, mods...)

	return Channels(queryMods...)
}

// LoadChannel allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (podcastShowL) LoadChannel(ctx context.Context, e boil.ContextExecutor, singular bool, maybePodcastShow interface{}, mods queries.Applicator) error {
	var slice []*PodcastShow
	var object *PodcastShow

	if singular {
		var ok bool
		object, ok = maybePodcastShow.(*PodcastShow)
		if !ok {
			object = new(PodcastShow)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePodcastShow)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePodcastShow))
			}
		}
	} else {
		s, ok := maybePodcastShow.(*[]*PodcastShow)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePodcastShow)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePodcastShow))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &podcastShowR{}
		}
		args[object.ChannelID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &podcastShowR{}
			}

			args[obj.ChannelID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`channels`),
		qm.WhereIn(`channels.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Channel")
	}

	var resultSlice []*Channel
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Channel")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for channels")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for channels")
	}

	if len(channelAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Channel = foreign
		if foreign.R == nil {
			foreign.R = &channelR{}
		}
		foreign.R.PodcastShow = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ChannelID == foreign.ID {
				local.R.Channel = foreign
				if foreign.R == nil {
					foreign.R = &channelR{}
				}
				foreign.R.PodcastShow = local
				break
			}
		}
	}

	return nil
}

// SetChannel of the podcastShow to the related item.
// Sets o.R.Channel to related.
// Adds o to related.R.PodcastShow.
func (o *PodcastShow) SetChannel(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Channel) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"podcast_shows\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"channel_id"}),
		strmangle.WhereClause("\"", "\"", 0, podcastShowPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ChannelID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ChannelID = related.ID
	if o.R == nil {
		o.R = &podcastShowR{
			Channel: related,
		}
	} else {
		o.R.Channel = related
	}

	if related.R == nil {
		related.R = &channelR{
			PodcastShow: o,
		}
	} else {
		related.R.PodcastShow = o
	}

	return nil
}

// PodcastShows retrieves all the records using an executor.
func PodcastShows(mods ...qm.QueryMod) podcastShowQuery {
	mods = append(mods, qm.From("\"podcast_shows\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"podcast_shows\".*"})
	}

	return podcastShowQuery{q}
}

// FindPodcastShow retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPodcastShow(ctx context.Context, exec boil.ContextExecutor, channelID string, selectCols ...string) (*PodcastShow, error) {
	podcastShowObj := &PodcastShow{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"podcast_shows\" where \"channel_id\"=?", sel,
	)

	q := queries.Raw(query, channelID)

	err := q.Bind(ctx, exec, podcastShowObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from podcast_shows")
	}

	if err = podcastShowObj.doAfterSelectHooks(ctx, exec); err != nil {
		return podcastShowObj, err
	}

	return podcastShowObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PodcastShow) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no podcast_shows provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(podcastShowColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	podcastShowInsertCacheMut.RLock()
	cache, cached := podcastShowInsertCache[key]
	podcastShowInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			podcastShowAllColumns,
			podcastShowColumnsWithDefault,
			podcastShowColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(podcastShowType, podcastShowMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(podcastShowType, podcastShowMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"podcast_shows\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"podcast_shows\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into podcast_shows")
	}

	if !cached {
		podcastShowInsertCacheMut.Lock()
		podcastShowInsertCache[key] = cache
		podcastShowInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PodcastShow.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PodcastShow) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	podcastShowUpdateCacheMut.RLock()
	cache, cached := podcastShowUpdateCache[key]
	podcastShowUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			podcastShowAllColumns,
			podcastShowPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update podcast_shows, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"podcast_shows\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, podcastShowPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(podcastShowType, podcastShowMapping, append(wl, podcastShowPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update podcast_shows row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for podcast_shows")
	}

	if !cached {
		podcastShowUpdateCacheMut.Lock()
		podcastShowUpdateCache[key] = cache
		podcastShowUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q podcastShowQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for podcast_shows")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for podcast_shows")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PodcastShowSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastShowPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"podcast_shows\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastShowPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in podcastShow slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all podcastShow")
	}
	return rowsAff, nil
}

// Delete deletes a single PodcastShow record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PodcastShow) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PodcastShow provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), podcastShowPrimaryKeyMapping)
	sql := "DELETE FROM \"podcast_shows\" WHERE \"channel_id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from podcast_shows")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for podcast_shows")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q podcastShowQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no podcastShowQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from podcast_shows")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for podcast_shows")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PodcastShowSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(podcastShowBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastShowPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"podcast_shows\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastShowPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from podcastShow slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for podcast_shows")
	}

	if len(podcastShowAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PodcastShow) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPodcastShow(ctx, exec, o.ChannelID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PodcastShowSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PodcastShowSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastShowPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"podcast_shows\".* FROM \"podcast_shows\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastShowPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PodcastShowSlice")
	}

	*o = slice

	return nil
}

// PodcastShowExists checks if the PodcastShow row exists.
func PodcastShowExists(ctx context.Context, exec boil.ContextExecutor, channelID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"podcast_shows\" where \"channel_id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, channelID)
	}
	row := exec.QueryRowContext(ctx, sql, channelID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if podcast_shows exists")
	}

	return exists, nil
}

// Exists checks if the PodcastShow row exists.
func (o *PodcastShow) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PodcastShowExists(ctx, exec, o.ChannelID)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PodcastShow) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no podcast_shows provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(podcastShowColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	podcastShowUpsertCacheMut.RLock()
	cache, cached := podcastShowUpsertCache[key]
	podcastShowUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			podcastShowAllColumns,
			podcastShowColumnsWithDefault,
			podcastShowColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			podcastShowAllColumns,
			podcastShowPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert podcast_shows, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(podcastShowPrimaryKeyColumns))
			copy(conflict, podcastShowPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"podcast_shows\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(podcastShowType, podcastShowMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(podcastShowType, podcastShowMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert podcast_shows")
	}

	if !cached {
		podcastShowUpsertCacheMut.Lock()
		podcastShowUpsertCache[key] = cache
		podcastShowUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
