// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PodcastEpisodeSegment is an object representing the database table.
type PodcastEpisodeSegment struct {
	ID         string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	VideoID    string      `boil:"video_id" json:"video_id" toml:"video_id" yaml:"video_id"`
	AnalysisID null.String `boil:"analysis_id" json:"analysis_id,omitempty" toml:"analysis_id" yaml:"analysis_id,omitempty"`
	Source     string      `boil:"source" json:"source" toml:"source" yaml:"source"`
	Position   int64       `boil:"position" json:"position" toml:"position" yaml:"position"`
	Category   string      `boil:"category" json:"category" toml:"category" yaml:"category"`
	StartMS    int64       `boil:"start_ms" json:"start_ms" toml:"start_ms" yaml:"start_ms"`
	EndMS      int64       `boil:"end_ms" json:"end_ms" toml:"end_ms" yaml:"end_ms"`
	StartCue   int64       `boil:"start_cue" json:"start_cue" toml:"start_cue" yaml:"start_cue"`
	EndCue     int64       `boil:"end_cue" json:"end_cue" toml:"end_cue" yaml:"end_cue"`
	StartText  string      `boil:"start_text" json:"start_text" toml:"start_text" yaml:"start_text"`
	EndText    string      `boil:"end_text" json:"end_text" toml:"end_text" yaml:"end_text"`
	Reason     string      `boil:"reason" json:"reason" toml:"reason" yaml:"reason"`
	Brand      null.String `boil:"brand" json:"brand,omitempty" toml:"brand" yaml:"brand,omitempty"`

	R *podcastEpisodeSegmentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L podcastEpisodeSegmentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PodcastEpisodeSegmentColumns = struct {
	ID         string
	VideoID    string
	AnalysisID string
	Source     string
	Position   string
	Category   string
	StartMS    string
	EndMS      string
	StartCue   string
	EndCue     string
	StartText  string
	EndText    string
	Reason     string
	Brand      string
}{
	ID:         "id",
	VideoID:    "video_id",
	AnalysisID: "analysis_id",
	Source:     "source",
	Position:   "position",
	Category:   "category",
	StartMS:    "start_ms",
	EndMS:      "end_ms",
	StartCue:   "start_cue",
	EndCue:     "end_cue",
	StartText:  "start_text",
	EndText:    "end_text",
	Reason:     "reason",
	Brand:      "brand",
}

var PodcastEpisodeSegmentTableColumns = struct {
	ID         string
	VideoID    string
	AnalysisID string
	Source     string
	Position   string
	Category   string
	StartMS    string
	EndMS      string
	StartCue   string
	EndCue     string
	StartText  string
	EndText    string
	Reason     string
	Brand      string
}{
	ID:         "podcast_episode_segments.id",
	VideoID:    "podcast_episode_segments.video_id",
	AnalysisID: "podcast_episode_segments.analysis_id",
	Source:     "podcast_episode_segments.source",
	Position:   "podcast_episode_segments.position",
	Category:   "podcast_episode_segments.category",
	StartMS:    "podcast_episode_segments.start_ms",
	EndMS:      "podcast_episode_segments.end_ms",
	StartCue:   "podcast_episode_segments.start_cue",
	EndCue:     "podcast_episode_segments.end_cue",
	StartText:  "podcast_episode_segments.start_text",
	EndText:    "podcast_episode_segments.end_text",
	Reason:     "podcast_episode_segments.reason",
	Brand:      "podcast_episode_segments.brand",
}

// Generated where

var PodcastEpisodeSegmentWhere = struct {
	ID         whereHelperstring
	VideoID    whereHelperstring
	AnalysisID whereHelpernull_String
	Source     whereHelperstring
	Position   whereHelperint64
	Category   whereHelperstring
	StartMS    whereHelperint64
	EndMS      whereHelperint64
	StartCue   whereHelperint64
	EndCue     whereHelperint64
	StartText  whereHelperstring
	EndText    whereHelperstring
	Reason     whereHelperstring
	Brand      whereHelpernull_String
}{
	ID:         whereHelperstring{field: "\"podcast_episode_segments\".\"id\""},
	VideoID:    whereHelperstring{field: "\"podcast_episode_segments\".\"video_id\""},
	AnalysisID: whereHelpernull_String{field: "\"podcast_episode_segments\".\"analysis_id\""},
	Source:     whereHelperstring{field: "\"podcast_episode_segments\".\"source\""},
	Position:   whereHelperint64{field: "\"podcast_episode_segments\".\"position\""},
	Category:   whereHelperstring{field: "\"podcast_episode_segments\".\"category\""},
	StartMS:    whereHelperint64{field: "\"podcast_episode_segments\".\"start_ms\""},
	EndMS:      whereHelperint64{field: "\"podcast_episode_segments\".\"end_ms\""},
	StartCue:   whereHelperint64{field: "\"podcast_episode_segments\".\"start_cue\""},
	EndCue:     whereHelperint64{field: "\"podcast_episode_segments\".\"end_cue\""},
	StartText:  whereHelperstring{field: "\"podcast_episode_segments\".\"start_text\""},
	EndText:    whereHelperstring{field: "\"podcast_episode_segments\".\"end_text\""},
	Reason:     whereHelperstring{field: "\"podcast_episode_segments\".\"reason\""},
	Brand:      whereHelpernull_String{field: "\"podcast_episode_segments\".\"brand\""},
}

// PodcastEpisodeSegmentRels is where relationship names are stored.
var PodcastEpisodeSegmentRels = struct {
	Analysis string
	Video    string
}{
	Analysis: "Analysis",
	Video:    "Video",
}

// podcastEpisodeSegmentR is where relationships are stored.
type podcastEpisodeSegmentR struct {
	Analysis *PodcastSegmentAnalysis `boil:"Analysis" json:"Analysis" toml:"Analysis" yaml:"Analysis"`
	Video    *Video                  `boil:"Video" json:"Video" toml:"Video" yaml:"Video"`
}

// NewStruct creates a new relationship struct
func (*podcastEpisodeSegmentR) NewStruct() *podcastEpisodeSegmentR {
	return &podcastEpisodeSegmentR{}
}

func (o *PodcastEpisodeSegment) GetAnalysis() *PodcastSegmentAnalysis {
	if o == nil {
		return nil
	}

	return o.R.GetAnalysis()
}

func (r *podcastEpisodeSegmentR) GetAnalysis() *PodcastSegmentAnalysis {
	if r == nil {
		return nil
	}

	return r.Analysis
}

func (o *PodcastEpisodeSegment) GetVideo() *Video {
	if o == nil {
		return nil
	}

	return o.R.GetVideo()
}

func (r *podcastEpisodeSegmentR) GetVideo() *Video {
	if r == nil {
		return nil
	}

	return r.Video
}

// podcastEpisodeSegmentL is where Load methods for each relationship are stored.
type podcastEpisodeSegmentL struct{}

var (
	podcastEpisodeSegmentAllColumns            = []string{"id", "video_id", "analysis_id", "source", "position", "category", "start_ms", "end_ms", "start_cue", "end_cue", "start_text", "end_text", "reason", "brand"}
	podcastEpisodeSegmentColumnsWithoutDefault = []string{"id", "video_id", "analysis_id", "source", "position", "category", "start_ms", "end_ms", "start_cue", "end_cue", "start_text", "end_text", "reason", "brand"}
	podcastEpisodeSegmentColumnsWithDefault    = []string{}
	podcastEpisodeSegmentPrimaryKeyColumns     = []string{"id"}
	podcastEpisodeSegmentGeneratedColumns      = []string{}
)

type (
	// PodcastEpisodeSegmentSlice is an alias for a slice of pointers to PodcastEpisodeSegment.
	// This should almost always be used instead of []PodcastEpisodeSegment.
	PodcastEpisodeSegmentSlice []*PodcastEpisodeSegment
	// PodcastEpisodeSegmentHook is the signature for custom PodcastEpisodeSegment hook methods
	PodcastEpisodeSegmentHook func(context.Context, boil.ContextExecutor, *PodcastEpisodeSegment) error

	podcastEpisodeSegmentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	podcastEpisodeSegmentType                 = reflect.TypeOf(&PodcastEpisodeSegment{})
	podcastEpisodeSegmentMapping              = queries.MakeStructMapping(podcastEpisodeSegmentType)
	podcastEpisodeSegmentPrimaryKeyMapping, _ = queries.BindMapping(podcastEpisodeSegmentType, podcastEpisodeSegmentMapping, podcastEpisodeSegmentPrimaryKeyColumns)
	podcastEpisodeSegmentInsertCacheMut       sync.RWMutex
	podcastEpisodeSegmentInsertCache          = make(map[string]insertCache)
	podcastEpisodeSegmentUpdateCacheMut       sync.RWMutex
	podcastEpisodeSegmentUpdateCache          = make(map[string]updateCache)
	podcastEpisodeSegmentUpsertCacheMut       sync.RWMutex
	podcastEpisodeSegmentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var podcastEpisodeSegmentAfterSelectMu sync.Mutex
var podcastEpisodeSegmentAfterSelectHooks []PodcastEpisodeSegmentHook

var podcastEpisodeSegmentBeforeInsertMu sync.Mutex
var podcastEpisodeSegmentBeforeInsertHooks []PodcastEpisodeSegmentHook
var podcastEpisodeSegmentAfterInsertMu sync.Mutex
var podcastEpisodeSegmentAfterInsertHooks []PodcastEpisodeSegmentHook

var podcastEpisodeSegmentBeforeUpdateMu sync.Mutex
var podcastEpisodeSegmentBeforeUpdateHooks []PodcastEpisodeSegmentHook
var podcastEpisodeSegmentAfterUpdateMu sync.Mutex
var podcastEpisodeSegmentAfterUpdateHooks []PodcastEpisodeSegmentHook

var podcastEpisodeSegmentBeforeDeleteMu sync.Mutex
var podcastEpisodeSegmentBeforeDeleteHooks []PodcastEpisodeSegmentHook
var podcastEpisodeSegmentAfterDeleteMu sync.Mutex
var podcastEpisodeSegmentAfterDeleteHooks []PodcastEpisodeSegmentHook

var podcastEpisodeSegmentBeforeUpsertMu sync.Mutex
var podcastEpisodeSegmentBeforeUpsertHooks []PodcastEpisodeSegmentHook
var podcastEpisodeSegmentAfterUpsertMu sync.Mutex
var podcastEpisodeSegmentAfterUpsertHooks []PodcastEpisodeSegmentHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PodcastEpisodeSegment) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastEpisodeSegmentAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PodcastEpisodeSegment) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastEpisodeSegmentBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PodcastEpisodeSegment) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastEpisodeSegmentAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PodcastEpisodeSegment) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastEpisodeSegmentBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PodcastEpisodeSegment) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastEpisodeSegmentAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PodcastEpisodeSegment) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastEpisodeSegmentBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PodcastEpisodeSegment) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastEpisodeSegmentAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PodcastEpisodeSegment) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastEpisodeSegmentBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PodcastEpisodeSegment) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range podcastEpisodeSegmentAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPodcastEpisodeSegmentHook registers your hook function for all future operations.
func AddPodcastEpisodeSegmentHook(hookPoint boil.HookPoint, podcastEpisodeSegmentHook PodcastEpisodeSegmentHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		podcastEpisodeSegmentAfterSelectMu.Lock()
		podcastEpisodeSegmentAfterSelectHooks = append(podcastEpisodeSegmentAfterSelectHooks, podcastEpisodeSegmentHook)
		podcastEpisodeSegmentAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		podcastEpisodeSegmentBeforeInsertMu.Lock()
		podcastEpisodeSegmentBeforeInsertHooks = append(podcastEpisodeSegmentBeforeInsertHooks, podcastEpisodeSegmentHook)
		podcastEpisodeSegmentBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		podcastEpisodeSegmentAfterInsertMu.Lock()
		podcastEpisodeSegmentAfterInsertHooks = append(podcastEpisodeSegmentAfterInsertHooks, podcastEpisodeSegmentHook)
		podcastEpisodeSegmentAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		podcastEpisodeSegmentBeforeUpdateMu.Lock()
		podcastEpisodeSegmentBeforeUpdateHooks = append(podcastEpisodeSegmentBeforeUpdateHooks, podcastEpisodeSegmentHook)
		podcastEpisodeSegmentBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		podcastEpisodeSegmentAfterUpdateMu.Lock()
		podcastEpisodeSegmentAfterUpdateHooks = append(podcastEpisodeSegmentAfterUpdateHooks, podcastEpisodeSegmentHook)
		podcastEpisodeSegmentAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		podcastEpisodeSegmentBeforeDeleteMu.Lock()
		podcastEpisodeSegmentBeforeDeleteHooks = append(podcastEpisodeSegmentBeforeDeleteHooks, podcastEpisodeSegmentHook)
		podcastEpisodeSegmentBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		podcastEpisodeSegmentAfterDeleteMu.Lock()
		podcastEpisodeSegmentAfterDeleteHooks = append(podcastEpisodeSegmentAfterDeleteHooks, podcastEpisodeSegmentHook)
		podcastEpisodeSegmentAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		podcastEpisodeSegmentBeforeUpsertMu.Lock()
		podcastEpisodeSegmentBeforeUpsertHooks = append(podcastEpisodeSegmentBeforeUpsertHooks, podcastEpisodeSegmentHook)
		podcastEpisodeSegmentBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		podcastEpisodeSegmentAfterUpsertMu.Lock()
		podcastEpisodeSegmentAfterUpsertHooks = append(podcastEpisodeSegmentAfterUpsertHooks, podcastEpisodeSegmentHook)
		podcastEpisodeSegmentAfterUpsertMu.Unlock()
	}
}

// One returns a single podcastEpisodeSegment record from the query.
func (q podcastEpisodeSegmentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PodcastEpisodeSegment, error) {
	o := &PodcastEpisodeSegment{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for podcast_episode_segments")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PodcastEpisodeSegment records from the query.
func (q podcastEpisodeSegmentQuery) All(ctx context.Context, exec boil.ContextExecutor) (PodcastEpisodeSegmentSlice, error) {
	var o []*PodcastEpisodeSegment

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PodcastEpisodeSegment slice")
	}

	if len(podcastEpisodeSegmentAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PodcastEpisodeSegment records in the query.
func (q podcastEpisodeSegmentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count podcast_episode_segments rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q podcastEpisodeSegmentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if podcast_episode_segments exists")
	}

	return count > 0, nil
}

// Analysis pointed to by the foreign key.
func (o *PodcastEpisodeSegment) Analysis(mods ...qm.QueryMod) podcastSegmentAnalysisQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AnalysisID),
	}

	queryMods = append(queryMods, mods...)

	return PodcastSegmentAnalyses(queryMods...)
}

// Video pointed to by the foreign key.
func (o *PodcastEpisodeSegment) Video(mods ...qm.QueryMod) videoQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.VideoID),
	}

	queryMods = append(queryMods, mods...)

	return Videos(queryMods...)
}

// LoadAnalysis allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (podcastEpisodeSegmentL) LoadAnalysis(ctx context.Context, e boil.ContextExecutor, singular bool, maybePodcastEpisodeSegment interface{}, mods queries.Applicator) error {
	var slice []*PodcastEpisodeSegment
	var object *PodcastEpisodeSegment

	if singular {
		var ok bool
		object, ok = maybePodcastEpisodeSegment.(*PodcastEpisodeSegment)
		if !ok {
			object = new(PodcastEpisodeSegment)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePodcastEpisodeSegment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePodcastEpisodeSegment))
			}
		}
	} else {
		s, ok := maybePodcastEpisodeSegment.(*[]*PodcastEpisodeSegment)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePodcastEpisodeSegment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePodcastEpisodeSegment))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &podcastEpisodeSegmentR{}
		}
		if !queries.IsNil(object.AnalysisID) {
			args[object.AnalysisID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &podcastEpisodeSegmentR{}
			}

			if !queries.IsNil(obj.AnalysisID) {
				args[obj.AnalysisID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`podcast_segment_analyses`),
		qm.WhereIn(`podcast_segment_analyses.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load PodcastSegmentAnalysis")
	}

	var resultSlice []*PodcastSegmentAnalysis
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice PodcastSegmentAnalysis")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for podcast_segment_analyses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for podcast_segment_analyses")
	}

	if len(podcastSegmentAnalysisAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Analysis = foreign
		if foreign.R == nil {
			foreign.R = &podcastSegmentAnalysisR{}
		}
		foreign.R.AnalysisPodcastEpisodeSegments = append(foreign.R.AnalysisPodcastEpisodeSegments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.AnalysisID, foreign.ID) {
				local.R.Analysis = foreign
				if foreign.R == nil {
					foreign.R = &podcastSegmentAnalysisR{}
				}
				foreign.R.AnalysisPodcastEpisodeSegments = append(foreign.R.AnalysisPodcastEpisodeSegments, local)
				break
			}
		}
	}

	return nil
}

// LoadVideo allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (podcastEpisodeSegmentL) LoadVideo(ctx context.Context, e boil.ContextExecutor, singular bool, maybePodcastEpisodeSegment interface{}, mods queries.Applicator) error {
	var slice []*PodcastEpisodeSegment
	var object *PodcastEpisodeSegment

	if singular {
		var ok bool
		object, ok = maybePodcastEpisodeSegment.(*PodcastEpisodeSegment)
		if !ok {
			object = new(PodcastEpisodeSegment)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePodcastEpisodeSegment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePodcastEpisodeSegment))
			}
		}
	} else {
		s, ok := maybePodcastEpisodeSegment.(*[]*PodcastEpisodeSegment)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePodcastEpisodeSegment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePodcastEpisodeSegment))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &podcastEpisodeSegmentR{}
		}
		args[object.VideoID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &podcastEpisodeSegmentR{}
			}

			args[obj.VideoID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`videos`),
		qm.WhereIn(`videos.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Video")
	}

	var resultSlice []*Video
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Video")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for videos")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for videos")
	}

	if len(videoAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Video = foreign
		if foreign.R == nil {
			foreign.R = &videoR{}
		}
		foreign.R.PodcastEpisodeSegments = append(foreign.R.PodcastEpisodeSegments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.VideoID == foreign.ID {
				local.R.Video = foreign
				if foreign.R == nil {
					foreign.R = &videoR{}
				}
				foreign.R.PodcastEpisodeSegments = append(foreign.R.PodcastEpisodeSegments, local)
				break
			}
		}
	}

	return nil
}

// SetAnalysis of the podcastEpisodeSegment to the related item.
// Sets o.R.Analysis to related.
// Adds o to related.R.AnalysisPodcastEpisodeSegments.
func (o *PodcastEpisodeSegment) SetAnalysis(ctx context.Context, exec boil.ContextExecutor, insert bool, related *PodcastSegmentAnalysis) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"podcast_episode_segments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"analysis_id"}),
		strmangle.WhereClause("\"", "\"", 0, podcastEpisodeSegmentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.AnalysisID, related.ID)
	if o.R == nil {
		o.R = &podcastEpisodeSegmentR{
			Analysis: related,
		}
	} else {
		o.R.Analysis = related
	}

	if related.R == nil {
		related.R = &podcastSegmentAnalysisR{
			AnalysisPodcastEpisodeSegments: PodcastEpisodeSegmentSlice{o},
		}
	} else {
		related.R.AnalysisPodcastEpisodeSegments = append(related.R.AnalysisPodcastEpisodeSegments, o)
	}

	return nil
}

// RemoveAnalysis relationship.
// Sets o.R.Analysis to nil.
// Removes o from all passed in related items' relationships struct.
func (o *PodcastEpisodeSegment) RemoveAnalysis(ctx context.Context, exec boil.ContextExecutor, related *PodcastSegmentAnalysis) error {
	var err error

	queries.SetScanner(&o.AnalysisID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("analysis_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Analysis = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.AnalysisPodcastEpisodeSegments {
		if queries.Equal(o.AnalysisID, ri.AnalysisID) {
			continue
		}

		ln := len(related.R.AnalysisPodcastEpisodeSegments)
		if ln > 1 && i < ln-1 {
			related.R.AnalysisPodcastEpisodeSegments[i] = related.R.AnalysisPodcastEpisodeSegments[ln-1]
		}
		related.R.AnalysisPodcastEpisodeSegments = related.R.AnalysisPodcastEpisodeSegments[:ln-1]
		break
	}
	return nil
}

// SetVideo of the podcastEpisodeSegment to the related item.
// Sets o.R.Video to related.
// Adds o to related.R.PodcastEpisodeSegments.
func (o *PodcastEpisodeSegment) SetVideo(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Video) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"podcast_episode_segments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"video_id"}),
		strmangle.WhereClause("\"", "\"", 0, podcastEpisodeSegmentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.VideoID = related.ID
	if o.R == nil {
		o.R = &podcastEpisodeSegmentR{
			Video: related,
		}
	} else {
		o.R.Video = related
	}

	if related.R == nil {
		related.R = &videoR{
			PodcastEpisodeSegments: PodcastEpisodeSegmentSlice{o},
		}
	} else {
		related.R.PodcastEpisodeSegments = append(related.R.PodcastEpisodeSegments, o)
	}

	return nil
}

// PodcastEpisodeSegments retrieves all the records using an executor.
func PodcastEpisodeSegments(mods ...qm.QueryMod) podcastEpisodeSegmentQuery {
	mods = append(mods, qm.From("\"podcast_episode_segments\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"podcast_episode_segments\".*"})
	}

	return podcastEpisodeSegmentQuery{q}
}

// FindPodcastEpisodeSegment retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPodcastEpisodeSegment(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*PodcastEpisodeSegment, error) {
	podcastEpisodeSegmentObj := &PodcastEpisodeSegment{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"podcast_episode_segments\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, podcastEpisodeSegmentObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from podcast_episode_segments")
	}

	if err = podcastEpisodeSegmentObj.doAfterSelectHooks(ctx, exec); err != nil {
		return podcastEpisodeSegmentObj, err
	}

	return podcastEpisodeSegmentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PodcastEpisodeSegment) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no podcast_episode_segments provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(podcastEpisodeSegmentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	podcastEpisodeSegmentInsertCacheMut.RLock()
	cache, cached := podcastEpisodeSegmentInsertCache[key]
	podcastEpisodeSegmentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			podcastEpisodeSegmentAllColumns,
			podcastEpisodeSegmentColumnsWithDefault,
			podcastEpisodeSegmentColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(podcastEpisodeSegmentType, podcastEpisodeSegmentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(podcastEpisodeSegmentType, podcastEpisodeSegmentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"podcast_episode_segments\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"podcast_episode_segments\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into podcast_episode_segments")
	}

	if !cached {
		podcastEpisodeSegmentInsertCacheMut.Lock()
		podcastEpisodeSegmentInsertCache[key] = cache
		podcastEpisodeSegmentInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PodcastEpisodeSegment.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PodcastEpisodeSegment) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	podcastEpisodeSegmentUpdateCacheMut.RLock()
	cache, cached := podcastEpisodeSegmentUpdateCache[key]
	podcastEpisodeSegmentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			podcastEpisodeSegmentAllColumns,
			podcastEpisodeSegmentPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update podcast_episode_segments, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"podcast_episode_segments\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, podcastEpisodeSegmentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(podcastEpisodeSegmentType, podcastEpisodeSegmentMapping, append(wl, podcastEpisodeSegmentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update podcast_episode_segments row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for podcast_episode_segments")
	}

	if !cached {
		podcastEpisodeSegmentUpdateCacheMut.Lock()
		podcastEpisodeSegmentUpdateCache[key] = cache
		podcastEpisodeSegmentUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q podcastEpisodeSegmentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for podcast_episode_segments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for podcast_episode_segments")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PodcastEpisodeSegmentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastEpisodeSegmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"podcast_episode_segments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastEpisodeSegmentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in podcastEpisodeSegment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all podcastEpisodeSegment")
	}
	return rowsAff, nil
}

// Delete deletes a single PodcastEpisodeSegment record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PodcastEpisodeSegment) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PodcastEpisodeSegment provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), podcastEpisodeSegmentPrimaryKeyMapping)
	sql := "DELETE FROM \"podcast_episode_segments\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from podcast_episode_segments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for podcast_episode_segments")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q podcastEpisodeSegmentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no podcastEpisodeSegmentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from podcast_episode_segments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for podcast_episode_segments")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PodcastEpisodeSegmentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(podcastEpisodeSegmentBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastEpisodeSegmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"podcast_episode_segments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastEpisodeSegmentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from podcastEpisodeSegment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for podcast_episode_segments")
	}

	if len(podcastEpisodeSegmentAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PodcastEpisodeSegment) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPodcastEpisodeSegment(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PodcastEpisodeSegmentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PodcastEpisodeSegmentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), podcastEpisodeSegmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"podcast_episode_segments\".* FROM \"podcast_episode_segments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, podcastEpisodeSegmentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PodcastEpisodeSegmentSlice")
	}

	*o = slice

	return nil
}

// PodcastEpisodeSegmentExists checks if the PodcastEpisodeSegment row exists.
func PodcastEpisodeSegmentExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"podcast_episode_segments\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if podcast_episode_segments exists")
	}

	return exists, nil
}

// Exists checks if the PodcastEpisodeSegment row exists.
func (o *PodcastEpisodeSegment) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PodcastEpisodeSegmentExists(ctx, exec, o.ID)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PodcastEpisodeSegment) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no podcast_episode_segments provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(podcastEpisodeSegmentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	podcastEpisodeSegmentUpsertCacheMut.RLock()
	cache, cached := podcastEpisodeSegmentUpsertCache[key]
	podcastEpisodeSegmentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			podcastEpisodeSegmentAllColumns,
			podcastEpisodeSegmentColumnsWithDefault,
			podcastEpisodeSegmentColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			podcastEpisodeSegmentAllColumns,
			podcastEpisodeSegmentPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert podcast_episode_segments, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(podcastEpisodeSegmentPrimaryKeyColumns))
			copy(conflict, podcastEpisodeSegmentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"podcast_episode_segments\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(podcastEpisodeSegmentType, podcastEpisodeSegmentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(podcastEpisodeSegmentType, podcastEpisodeSegmentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert podcast_episode_segments")
	}

	if !cached {
		podcastEpisodeSegmentUpsertCacheMut.Lock()
		podcastEpisodeSegmentUpsertCache[key] = cache
		podcastEpisodeSegmentUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
