// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testViews(t *testing.T) {
	t.Parallel()

	query := Views()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testViewsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Views().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testViewsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Views().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Views().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testViewsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ViewSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Views().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testViewsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ViewExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if View exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ViewExists to return true, but got false.")
	}
}

func testViewsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	viewFound, err := FindView(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if viewFound == nil {
		t.Error("want a record, got nil")
	}
}

func testViewsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Views().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testViewsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Views().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testViewsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	viewOne := &View{}
	viewTwo := &View{}
	if err = randomize.Struct(seed, viewOne, viewDBTypes, false, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}
	if err = randomize.Struct(seed, viewTwo, viewDBTypes, false, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = viewOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = viewTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Views().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testViewsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	viewOne := &View{}
	viewTwo := &View{}
	if err = randomize.Struct(seed, viewOne, viewDBTypes, false, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}
	if err = randomize.Struct(seed, viewTwo, viewDBTypes, false, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = viewOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = viewTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Views().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func viewBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *View) error {
	*o = View{}
	return nil
}

func viewAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *View) error {
	*o = View{}
	return nil
}

func viewAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *View) error {
	*o = View{}
	return nil
}

func viewBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *View) error {
	*o = View{}
	return nil
}

func viewAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *View) error {
	*o = View{}
	return nil
}

func viewBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *View) error {
	*o = View{}
	return nil
}

func viewAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *View) error {
	*o = View{}
	return nil
}

func viewBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *View) error {
	*o = View{}
	return nil
}

func viewAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *View) error {
	*o = View{}
	return nil
}

func testViewsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &View{}
	o := &View{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, viewDBTypes, false); err != nil {
		t.Errorf("Unable to randomize View object: %s", err)
	}

	AddViewHook(boil.BeforeInsertHook, viewBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	viewBeforeInsertHooks = []ViewHook{}

	AddViewHook(boil.AfterInsertHook, viewAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	viewAfterInsertHooks = []ViewHook{}

	AddViewHook(boil.AfterSelectHook, viewAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	viewAfterSelectHooks = []ViewHook{}

	AddViewHook(boil.BeforeUpdateHook, viewBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	viewBeforeUpdateHooks = []ViewHook{}

	AddViewHook(boil.AfterUpdateHook, viewAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	viewAfterUpdateHooks = []ViewHook{}

	AddViewHook(boil.BeforeDeleteHook, viewBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	viewBeforeDeleteHooks = []ViewHook{}

	AddViewHook(boil.AfterDeleteHook, viewAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	viewAfterDeleteHooks = []ViewHook{}

	AddViewHook(boil.BeforeUpsertHook, viewBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	viewBeforeUpsertHooks = []ViewHook{}

	AddViewHook(boil.AfterUpsertHook, viewAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	viewAfterUpsertHooks = []ViewHook{}
}

func testViewsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Views().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testViewsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(viewColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Views().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testViewToOneVideoUsingVideo(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local View
	var foreign Video

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, viewDBTypes, false, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, videoDBTypes, false, videoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Video struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.VideoID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Video().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddVideoHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Video) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ViewSlice{&local}
	if err = local.L.LoadVideo(ctx, tx, false, (*[]*View)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Video == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Video = nil
	if err = local.L.LoadVideo(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Video == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testViewToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local View
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, viewDBTypes, false, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ViewSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*View)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testViewToOneSetOpVideoUsingVideo(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a View
	var b, c Video

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, viewDBTypes, false, strmangle.SetComplement(viewPrimaryKeyColumns, viewColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, videoDBTypes, false, strmangle.SetComplement(videoPrimaryKeyColumns, videoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, videoDBTypes, false, strmangle.SetComplement(videoPrimaryKeyColumns, videoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Video{&b, &c} {
		err = a.SetVideo(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Video != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Views[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.VideoID != x.ID {
			t.Error("foreign key was wrong value", a.VideoID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.VideoID))
		reflect.Indirect(reflect.ValueOf(&a.VideoID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.VideoID != x.ID {
			t.Error("foreign key was wrong value", a.VideoID, x.ID)
		}
	}
}
func testViewToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a View
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, viewDBTypes, false, strmangle.SetComplement(viewPrimaryKeyColumns, viewColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Views[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testViewsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testViewsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ViewSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testViewsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Views().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	viewDBTypes = map[string]string{`ID`: `TEXT`, `CreatedAt`: `DATE`, `UpdatedAt`: `DATE`, `UserID`: `TEXT`, `VideoID`: `TEXT`, `Progress`: `INTEGER`}
	_           = bytes.MinRead
)

func testViewsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(viewPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(viewAllColumns) == len(viewPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Views().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, viewDBTypes, true, viewPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testViewsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(viewAllColumns) == len(viewPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &View{}
	if err = randomize.Struct(seed, o, viewDBTypes, true, viewColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Views().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, viewDBTypes, true, viewPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(viewAllColumns, viewPrimaryKeyColumns) {
		fields = viewAllColumns
	} else {
		fields = strmangle.SetComplement(
			viewAllColumns,
			viewPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ViewSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testViewsUpsert(t *testing.T) {
	t.Parallel()
	if len(viewAllColumns) == len(viewPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := View{}
	if err = randomize.Struct(seed, &o, viewDBTypes, true); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert View: %s", err)
	}

	count, err := Views().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, viewDBTypes, false, viewPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize View struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert View: %s", err)
	}

	count, err = Views().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
