// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testYoutubeTVSyncAccounts(t *testing.T) {
	t.Parallel()

	query := YoutubeTVSyncAccounts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testYoutubeTVSyncAccountsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := YoutubeTVSyncAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testYoutubeTVSyncAccountsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := YoutubeTVSyncAccounts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := YoutubeTVSyncAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testYoutubeTVSyncAccountsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := YoutubeTVSyncAccountSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := YoutubeTVSyncAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testYoutubeTVSyncAccountsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := YoutubeTVSyncAccountExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if YoutubeTVSyncAccount exists: %s", err)
	}
	if !e {
		t.Errorf("Expected YoutubeTVSyncAccountExists to return true, but got false.")
	}
}

func testYoutubeTVSyncAccountsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	youtubeTVSyncAccountFound, err := FindYoutubeTVSyncAccount(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if youtubeTVSyncAccountFound == nil {
		t.Error("want a record, got nil")
	}
}

func testYoutubeTVSyncAccountsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = YoutubeTVSyncAccounts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testYoutubeTVSyncAccountsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := YoutubeTVSyncAccounts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testYoutubeTVSyncAccountsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	youtubeTVSyncAccountOne := &YoutubeTVSyncAccount{}
	youtubeTVSyncAccountTwo := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, youtubeTVSyncAccountOne, youtubeTVSyncAccountDBTypes, false, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}
	if err = randomize.Struct(seed, youtubeTVSyncAccountTwo, youtubeTVSyncAccountDBTypes, false, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = youtubeTVSyncAccountOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = youtubeTVSyncAccountTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := YoutubeTVSyncAccounts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testYoutubeTVSyncAccountsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	youtubeTVSyncAccountOne := &YoutubeTVSyncAccount{}
	youtubeTVSyncAccountTwo := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, youtubeTVSyncAccountOne, youtubeTVSyncAccountDBTypes, false, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}
	if err = randomize.Struct(seed, youtubeTVSyncAccountTwo, youtubeTVSyncAccountDBTypes, false, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = youtubeTVSyncAccountOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = youtubeTVSyncAccountTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := YoutubeTVSyncAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func youtubeTVSyncAccountBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *YoutubeTVSyncAccount) error {
	*o = YoutubeTVSyncAccount{}
	return nil
}

func youtubeTVSyncAccountAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *YoutubeTVSyncAccount) error {
	*o = YoutubeTVSyncAccount{}
	return nil
}

func youtubeTVSyncAccountAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *YoutubeTVSyncAccount) error {
	*o = YoutubeTVSyncAccount{}
	return nil
}

func youtubeTVSyncAccountBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *YoutubeTVSyncAccount) error {
	*o = YoutubeTVSyncAccount{}
	return nil
}

func youtubeTVSyncAccountAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *YoutubeTVSyncAccount) error {
	*o = YoutubeTVSyncAccount{}
	return nil
}

func youtubeTVSyncAccountBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *YoutubeTVSyncAccount) error {
	*o = YoutubeTVSyncAccount{}
	return nil
}

func youtubeTVSyncAccountAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *YoutubeTVSyncAccount) error {
	*o = YoutubeTVSyncAccount{}
	return nil
}

func youtubeTVSyncAccountBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *YoutubeTVSyncAccount) error {
	*o = YoutubeTVSyncAccount{}
	return nil
}

func youtubeTVSyncAccountAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *YoutubeTVSyncAccount) error {
	*o = YoutubeTVSyncAccount{}
	return nil
}

func testYoutubeTVSyncAccountsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &YoutubeTVSyncAccount{}
	o := &YoutubeTVSyncAccount{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, false); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount object: %s", err)
	}

	AddYoutubeTVSyncAccountHook(boil.BeforeInsertHook, youtubeTVSyncAccountBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	youtubeTVSyncAccountBeforeInsertHooks = []YoutubeTVSyncAccountHook{}

	AddYoutubeTVSyncAccountHook(boil.AfterInsertHook, youtubeTVSyncAccountAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	youtubeTVSyncAccountAfterInsertHooks = []YoutubeTVSyncAccountHook{}

	AddYoutubeTVSyncAccountHook(boil.AfterSelectHook, youtubeTVSyncAccountAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	youtubeTVSyncAccountAfterSelectHooks = []YoutubeTVSyncAccountHook{}

	AddYoutubeTVSyncAccountHook(boil.BeforeUpdateHook, youtubeTVSyncAccountBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	youtubeTVSyncAccountBeforeUpdateHooks = []YoutubeTVSyncAccountHook{}

	AddYoutubeTVSyncAccountHook(boil.AfterUpdateHook, youtubeTVSyncAccountAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	youtubeTVSyncAccountAfterUpdateHooks = []YoutubeTVSyncAccountHook{}

	AddYoutubeTVSyncAccountHook(boil.BeforeDeleteHook, youtubeTVSyncAccountBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	youtubeTVSyncAccountBeforeDeleteHooks = []YoutubeTVSyncAccountHook{}

	AddYoutubeTVSyncAccountHook(boil.AfterDeleteHook, youtubeTVSyncAccountAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	youtubeTVSyncAccountAfterDeleteHooks = []YoutubeTVSyncAccountHook{}

	AddYoutubeTVSyncAccountHook(boil.BeforeUpsertHook, youtubeTVSyncAccountBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	youtubeTVSyncAccountBeforeUpsertHooks = []YoutubeTVSyncAccountHook{}

	AddYoutubeTVSyncAccountHook(boil.AfterUpsertHook, youtubeTVSyncAccountAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	youtubeTVSyncAccountAfterUpsertHooks = []YoutubeTVSyncAccountHook{}
}

func testYoutubeTVSyncAccountsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := YoutubeTVSyncAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testYoutubeTVSyncAccountsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(youtubeTVSyncAccountPrimaryKeyColumns, youtubeTVSyncAccountColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := YoutubeTVSyncAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testYoutubeTVSyncAccountToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local YoutubeTVSyncAccount
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, youtubeTVSyncAccountDBTypes, false, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := YoutubeTVSyncAccountSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*YoutubeTVSyncAccount)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testYoutubeTVSyncAccountToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a YoutubeTVSyncAccount
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, youtubeTVSyncAccountDBTypes, false, strmangle.SetComplement(youtubeTVSyncAccountPrimaryKeyColumns, youtubeTVSyncAccountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.YoutubeTVSyncAccount != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testYoutubeTVSyncAccountsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testYoutubeTVSyncAccountsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := YoutubeTVSyncAccountSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testYoutubeTVSyncAccountsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := YoutubeTVSyncAccounts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	youtubeTVSyncAccountDBTypes = map[string]string{`ID`: `TEXT`, `CreatedAt`: `DATE`, `UpdatedAt`: `DATE`, `UserID`: `TEXT`, `ScreenID`: `TEXT`, `ScreenName`: `TEXT`, `LoungeTokenEnc`: `BLOB`, `EncSecretHash`: `TEXT`, `SyncEnabled`: `BOOLEAN`, `ConnectionState`: `TEXT`, `StateReason`: `TEXT`, `LastConnectedAt`: `DATE`, `LastEventAt`: `DATE`, `LastDisconnectAt`: `DATE`, `LastUserActivityAt`: `DATE`, `LastVideoID`: `TEXT`, `LastError`: `TEXT`}
	_                           = bytes.MinRead
)

func testYoutubeTVSyncAccountsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(youtubeTVSyncAccountPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(youtubeTVSyncAccountAllColumns) == len(youtubeTVSyncAccountPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := YoutubeTVSyncAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testYoutubeTVSyncAccountsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(youtubeTVSyncAccountAllColumns) == len(youtubeTVSyncAccountPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := YoutubeTVSyncAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, youtubeTVSyncAccountDBTypes, true, youtubeTVSyncAccountPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(youtubeTVSyncAccountAllColumns, youtubeTVSyncAccountPrimaryKeyColumns) {
		fields = youtubeTVSyncAccountAllColumns
	} else {
		fields = strmangle.SetComplement(
			youtubeTVSyncAccountAllColumns,
			youtubeTVSyncAccountPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := YoutubeTVSyncAccountSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testYoutubeTVSyncAccountsUpsert(t *testing.T) {
	t.Parallel()
	if len(youtubeTVSyncAccountAllColumns) == len(youtubeTVSyncAccountPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := YoutubeTVSyncAccount{}
	if err = randomize.Struct(seed, &o, youtubeTVSyncAccountDBTypes, true); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert YoutubeTVSyncAccount: %s", err)
	}

	count, err := YoutubeTVSyncAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, youtubeTVSyncAccountDBTypes, false, youtubeTVSyncAccountPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize YoutubeTVSyncAccount struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert YoutubeTVSyncAccount: %s", err)
	}

	count, err = YoutubeTVSyncAccounts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
