// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// YoutubeTVSyncAccount is an object representing the database table.
type YoutubeTVSyncAccount struct {
	ID                 string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt          time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt          time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	UserID             string      `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	ScreenID           string      `boil:"screen_id" json:"screen_id" toml:"screen_id" yaml:"screen_id"`
	ScreenName         string      `boil:"screen_name" json:"screen_name" toml:"screen_name" yaml:"screen_name"`
	LoungeTokenEnc     []byte      `boil:"lounge_token_enc" json:"lounge_token_enc" toml:"lounge_token_enc" yaml:"lounge_token_enc"`
	EncSecretHash      string      `boil:"enc_secret_hash" json:"enc_secret_hash" toml:"enc_secret_hash" yaml:"enc_secret_hash"`
	SyncEnabled        bool        `boil:"sync_enabled" json:"sync_enabled" toml:"sync_enabled" yaml:"sync_enabled"`
	ConnectionState    string      `boil:"connection_state" json:"connection_state" toml:"connection_state" yaml:"connection_state"`
	StateReason        string      `boil:"state_reason" json:"state_reason" toml:"state_reason" yaml:"state_reason"`
	LastConnectedAt    null.Time   `boil:"last_connected_at" json:"last_connected_at,omitempty" toml:"last_connected_at" yaml:"last_connected_at,omitempty"`
	LastEventAt        null.Time   `boil:"last_event_at" json:"last_event_at,omitempty" toml:"last_event_at" yaml:"last_event_at,omitempty"`
	LastDisconnectAt   null.Time   `boil:"last_disconnect_at" json:"last_disconnect_at,omitempty" toml:"last_disconnect_at" yaml:"last_disconnect_at,omitempty"`
	LastUserActivityAt null.Time   `boil:"last_user_activity_at" json:"last_user_activity_at,omitempty" toml:"last_user_activity_at" yaml:"last_user_activity_at,omitempty"`
	LastVideoID        null.String `boil:"last_video_id" json:"last_video_id,omitempty" toml:"last_video_id" yaml:"last_video_id,omitempty"`
	LastError          string      `boil:"last_error" json:"last_error" toml:"last_error" yaml:"last_error"`

	R *youtubeTVSyncAccountR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L youtubeTVSyncAccountL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var YoutubeTVSyncAccountColumns = struct {
	ID                 string
	CreatedAt          string
	UpdatedAt          string
	UserID             string
	ScreenID           string
	ScreenName         string
	LoungeTokenEnc     string
	EncSecretHash      string
	SyncEnabled        string
	ConnectionState    string
	StateReason        string
	LastConnectedAt    string
	LastEventAt        string
	LastDisconnectAt   string
	LastUserActivityAt string
	LastVideoID        string
	LastError          string
}{
	ID:                 "id",
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
	UserID:             "user_id",
	ScreenID:           "screen_id",
	ScreenName:         "screen_name",
	LoungeTokenEnc:     "lounge_token_enc",
	EncSecretHash:      "enc_secret_hash",
	SyncEnabled:        "sync_enabled",
	ConnectionState:    "connection_state",
	StateReason:        "state_reason",
	LastConnectedAt:    "last_connected_at",
	LastEventAt:        "last_event_at",
	LastDisconnectAt:   "last_disconnect_at",
	LastUserActivityAt: "last_user_activity_at",
	LastVideoID:        "last_video_id",
	LastError:          "last_error",
}

var YoutubeTVSyncAccountTableColumns = struct {
	ID                 string
	CreatedAt          string
	UpdatedAt          string
	UserID             string
	ScreenID           string
	ScreenName         string
	LoungeTokenEnc     string
	EncSecretHash      string
	SyncEnabled        string
	ConnectionState    string
	StateReason        string
	LastConnectedAt    string
	LastEventAt        string
	LastDisconnectAt   string
	LastUserActivityAt string
	LastVideoID        string
	LastError          string
}{
	ID:                 "youtube_tv_sync_accounts.id",
	CreatedAt:          "youtube_tv_sync_accounts.created_at",
	UpdatedAt:          "youtube_tv_sync_accounts.updated_at",
	UserID:             "youtube_tv_sync_accounts.user_id",
	ScreenID:           "youtube_tv_sync_accounts.screen_id",
	ScreenName:         "youtube_tv_sync_accounts.screen_name",
	LoungeTokenEnc:     "youtube_tv_sync_accounts.lounge_token_enc",
	EncSecretHash:      "youtube_tv_sync_accounts.enc_secret_hash",
	SyncEnabled:        "youtube_tv_sync_accounts.sync_enabled",
	ConnectionState:    "youtube_tv_sync_accounts.connection_state",
	StateReason:        "youtube_tv_sync_accounts.state_reason",
	LastConnectedAt:    "youtube_tv_sync_accounts.last_connected_at",
	LastEventAt:        "youtube_tv_sync_accounts.last_event_at",
	LastDisconnectAt:   "youtube_tv_sync_accounts.last_disconnect_at",
	LastUserActivityAt: "youtube_tv_sync_accounts.last_user_activity_at",
	LastVideoID:        "youtube_tv_sync_accounts.last_video_id",
	LastError:          "youtube_tv_sync_accounts.last_error",
}

// Generated where

var YoutubeTVSyncAccountWhere = struct {
	ID                 whereHelperstring
	CreatedAt          whereHelpertime_Time
	UpdatedAt          whereHelpertime_Time
	UserID             whereHelperstring
	ScreenID           whereHelperstring
	ScreenName         whereHelperstring
	LoungeTokenEnc     whereHelper__byte
	EncSecretHash      whereHelperstring
	SyncEnabled        whereHelperbool
	ConnectionState    whereHelperstring
	StateReason        whereHelperstring
	LastConnectedAt    whereHelpernull_Time
	LastEventAt        whereHelpernull_Time
	LastDisconnectAt   whereHelpernull_Time
	LastUserActivityAt whereHelpernull_Time
	LastVideoID        whereHelpernull_String
	LastError          whereHelperstring
}{
	ID:                 whereHelperstring{field: "\"youtube_tv_sync_accounts\".\"id\""},
	CreatedAt:          whereHelpertime_Time{field: "\"youtube_tv_sync_accounts\".\"created_at\""},
	UpdatedAt:          whereHelpertime_Time{field: "\"youtube_tv_sync_accounts\".\"updated_at\""},
	UserID:             whereHelperstring{field: "\"youtube_tv_sync_accounts\".\"user_id\""},
	ScreenID:           whereHelperstring{field: "\"youtube_tv_sync_accounts\".\"screen_id\""},
	ScreenName:         whereHelperstring{field: "\"youtube_tv_sync_accounts\".\"screen_name\""},
	LoungeTokenEnc:     whereHelper__byte{field: "\"youtube_tv_sync_accounts\".\"lounge_token_enc\""},
	EncSecretHash:      whereHelperstring{field: "\"youtube_tv_sync_accounts\".\"enc_secret_hash\""},
	SyncEnabled:        whereHelperbool{field: "\"youtube_tv_sync_accounts\".\"sync_enabled\""},
	ConnectionState:    whereHelperstring{field: "\"youtube_tv_sync_accounts\".\"connection_state\""},
	StateReason:        whereHelperstring{field: "\"youtube_tv_sync_accounts\".\"state_reason\""},
	LastConnectedAt:    whereHelpernull_Time{field: "\"youtube_tv_sync_accounts\".\"last_connected_at\""},
	LastEventAt:        whereHelpernull_Time{field: "\"youtube_tv_sync_accounts\".\"last_event_at\""},
	LastDisconnectAt:   whereHelpernull_Time{field: "\"youtube_tv_sync_accounts\".\"last_disconnect_at\""},
	LastUserActivityAt: whereHelpernull_Time{field: "\"youtube_tv_sync_accounts\".\"last_user_activity_at\""},
	LastVideoID:        whereHelpernull_String{field: "\"youtube_tv_sync_accounts\".\"last_video_id\""},
	LastError:          whereHelperstring{field: "\"youtube_tv_sync_accounts\".\"last_error\""},
}

// YoutubeTVSyncAccountRels is where relationship names are stored.
var YoutubeTVSyncAccountRels = struct {
	User string
}{
	User: "User",
}

// youtubeTVSyncAccountR is where relationships are stored.
type youtubeTVSyncAccountR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*youtubeTVSyncAccountR) NewStruct() *youtubeTVSyncAccountR {
	return &youtubeTVSyncAccountR{}
}

func (o *YoutubeTVSyncAccount) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *youtubeTVSyncAccountR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// youtubeTVSyncAccountL is where Load methods for each relationship are stored.
type youtubeTVSyncAccountL struct{}

var (
	youtubeTVSyncAccountAllColumns            = []string{"id", "created_at", "updated_at", "user_id", "screen_id", "screen_name", "lounge_token_enc", "enc_secret_hash", "sync_enabled", "connection_state", "state_reason", "last_connected_at", "last_event_at", "last_disconnect_at", "last_user_activity_at", "last_video_id", "last_error"}
	youtubeTVSyncAccountColumnsWithoutDefault = []string{"id", "created_at", "updated_at", "user_id", "screen_id", "lounge_token_enc", "enc_secret_hash"}
	youtubeTVSyncAccountColumnsWithDefault    = []string{"screen_name", "sync_enabled", "connection_state", "state_reason", "last_connected_at", "last_event_at", "last_disconnect_at", "last_user_activity_at", "last_video_id", "last_error"}
	youtubeTVSyncAccountPrimaryKeyColumns     = []string{"id"}
	youtubeTVSyncAccountGeneratedColumns      = []string{}
)

type (
	// YoutubeTVSyncAccountSlice is an alias for a slice of pointers to YoutubeTVSyncAccount.
	// This should almost always be used instead of []YoutubeTVSyncAccount.
	YoutubeTVSyncAccountSlice []*YoutubeTVSyncAccount
	// YoutubeTVSyncAccountHook is the signature for custom YoutubeTVSyncAccount hook methods
	YoutubeTVSyncAccountHook func(context.Context, boil.ContextExecutor, *YoutubeTVSyncAccount) error

	youtubeTVSyncAccountQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	youtubeTVSyncAccountType                 = reflect.TypeOf(&YoutubeTVSyncAccount{})
	youtubeTVSyncAccountMapping              = queries.MakeStructMapping(youtubeTVSyncAccountType)
	youtubeTVSyncAccountPrimaryKeyMapping, _ = queries.BindMapping(youtubeTVSyncAccountType, youtubeTVSyncAccountMapping, youtubeTVSyncAccountPrimaryKeyColumns)
	youtubeTVSyncAccountInsertCacheMut       sync.RWMutex
	youtubeTVSyncAccountInsertCache          = make(map[string]insertCache)
	youtubeTVSyncAccountUpdateCacheMut       sync.RWMutex
	youtubeTVSyncAccountUpdateCache          = make(map[string]updateCache)
	youtubeTVSyncAccountUpsertCacheMut       sync.RWMutex
	youtubeTVSyncAccountUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var youtubeTVSyncAccountAfterSelectMu sync.Mutex
var youtubeTVSyncAccountAfterSelectHooks []YoutubeTVSyncAccountHook

var youtubeTVSyncAccountBeforeInsertMu sync.Mutex
var youtubeTVSyncAccountBeforeInsertHooks []YoutubeTVSyncAccountHook
var youtubeTVSyncAccountAfterInsertMu sync.Mutex
var youtubeTVSyncAccountAfterInsertHooks []YoutubeTVSyncAccountHook

var youtubeTVSyncAccountBeforeUpdateMu sync.Mutex
var youtubeTVSyncAccountBeforeUpdateHooks []YoutubeTVSyncAccountHook
var youtubeTVSyncAccountAfterUpdateMu sync.Mutex
var youtubeTVSyncAccountAfterUpdateHooks []YoutubeTVSyncAccountHook

var youtubeTVSyncAccountBeforeDeleteMu sync.Mutex
var youtubeTVSyncAccountBeforeDeleteHooks []YoutubeTVSyncAccountHook
var youtubeTVSyncAccountAfterDeleteMu sync.Mutex
var youtubeTVSyncAccountAfterDeleteHooks []YoutubeTVSyncAccountHook

var youtubeTVSyncAccountBeforeUpsertMu sync.Mutex
var youtubeTVSyncAccountBeforeUpsertHooks []YoutubeTVSyncAccountHook
var youtubeTVSyncAccountAfterUpsertMu sync.Mutex
var youtubeTVSyncAccountAfterUpsertHooks []YoutubeTVSyncAccountHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *YoutubeTVSyncAccount) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeTVSyncAccountAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *YoutubeTVSyncAccount) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeTVSyncAccountBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *YoutubeTVSyncAccount) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeTVSyncAccountAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *YoutubeTVSyncAccount) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeTVSyncAccountBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *YoutubeTVSyncAccount) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeTVSyncAccountAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *YoutubeTVSyncAccount) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeTVSyncAccountBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *YoutubeTVSyncAccount) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeTVSyncAccountAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *YoutubeTVSyncAccount) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeTVSyncAccountBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *YoutubeTVSyncAccount) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeTVSyncAccountAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddYoutubeTVSyncAccountHook registers your hook function for all future operations.
func AddYoutubeTVSyncAccountHook(hookPoint boil.HookPoint, youtubeTVSyncAccountHook YoutubeTVSyncAccountHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		youtubeTVSyncAccountAfterSelectMu.Lock()
		youtubeTVSyncAccountAfterSelectHooks = append(youtubeTVSyncAccountAfterSelectHooks, youtubeTVSyncAccountHook)
		youtubeTVSyncAccountAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		youtubeTVSyncAccountBeforeInsertMu.Lock()
		youtubeTVSyncAccountBeforeInsertHooks = append(youtubeTVSyncAccountBeforeInsertHooks, youtubeTVSyncAccountHook)
		youtubeTVSyncAccountBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		youtubeTVSyncAccountAfterInsertMu.Lock()
		youtubeTVSyncAccountAfterInsertHooks = append(youtubeTVSyncAccountAfterInsertHooks, youtubeTVSyncAccountHook)
		youtubeTVSyncAccountAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		youtubeTVSyncAccountBeforeUpdateMu.Lock()
		youtubeTVSyncAccountBeforeUpdateHooks = append(youtubeTVSyncAccountBeforeUpdateHooks, youtubeTVSyncAccountHook)
		youtubeTVSyncAccountBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		youtubeTVSyncAccountAfterUpdateMu.Lock()
		youtubeTVSyncAccountAfterUpdateHooks = append(youtubeTVSyncAccountAfterUpdateHooks, youtubeTVSyncAccountHook)
		youtubeTVSyncAccountAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		youtubeTVSyncAccountBeforeDeleteMu.Lock()
		youtubeTVSyncAccountBeforeDeleteHooks = append(youtubeTVSyncAccountBeforeDeleteHooks, youtubeTVSyncAccountHook)
		youtubeTVSyncAccountBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		youtubeTVSyncAccountAfterDeleteMu.Lock()
		youtubeTVSyncAccountAfterDeleteHooks = append(youtubeTVSyncAccountAfterDeleteHooks, youtubeTVSyncAccountHook)
		youtubeTVSyncAccountAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		youtubeTVSyncAccountBeforeUpsertMu.Lock()
		youtubeTVSyncAccountBeforeUpsertHooks = append(youtubeTVSyncAccountBeforeUpsertHooks, youtubeTVSyncAccountHook)
		youtubeTVSyncAccountBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		youtubeTVSyncAccountAfterUpsertMu.Lock()
		youtubeTVSyncAccountAfterUpsertHooks = append(youtubeTVSyncAccountAfterUpsertHooks, youtubeTVSyncAccountHook)
		youtubeTVSyncAccountAfterUpsertMu.Unlock()
	}
}

// One returns a single youtubeTVSyncAccount record from the query.
func (q youtubeTVSyncAccountQuery) One(ctx context.Context, exec boil.ContextExecutor) (*YoutubeTVSyncAccount, error) {
	o := &YoutubeTVSyncAccount{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for youtube_tv_sync_accounts")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all YoutubeTVSyncAccount records from the query.
func (q youtubeTVSyncAccountQuery) All(ctx context.Context, exec boil.ContextExecutor) (YoutubeTVSyncAccountSlice, error) {
	var o []*YoutubeTVSyncAccount

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to YoutubeTVSyncAccount slice")
	}

	if len(youtubeTVSyncAccountAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all YoutubeTVSyncAccount records in the query.
func (q youtubeTVSyncAccountQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count youtube_tv_sync_accounts rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q youtubeTVSyncAccountQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if youtube_tv_sync_accounts exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *YoutubeTVSyncAccount) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (youtubeTVSyncAccountL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeYoutubeTVSyncAccount any, mods queries.Applicator) error {
	var slice []*YoutubeTVSyncAccount
	var object *YoutubeTVSyncAccount

	if singular {
		var ok bool
		object, ok = maybeYoutubeTVSyncAccount.(*YoutubeTVSyncAccount)
		if !ok {
			object = new(YoutubeTVSyncAccount)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeYoutubeTVSyncAccount)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeYoutubeTVSyncAccount))
			}
		}
	} else {
		s, ok := maybeYoutubeTVSyncAccount.(*[]*YoutubeTVSyncAccount)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeYoutubeTVSyncAccount)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeYoutubeTVSyncAccount))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &youtubeTVSyncAccountR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &youtubeTVSyncAccountR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.YoutubeTVSyncAccount = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.YoutubeTVSyncAccount = local
				break
			}
		}
	}

	return nil
}

// SetUser of the youtubeTVSyncAccount to the related item.
// Sets o.R.User to related.
// Adds o to related.R.YoutubeTVSyncAccount.
func (o *YoutubeTVSyncAccount) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"youtube_tv_sync_accounts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 0, youtubeTVSyncAccountPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &youtubeTVSyncAccountR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			YoutubeTVSyncAccount: o,
		}
	} else {
		related.R.YoutubeTVSyncAccount = o
	}

	return nil
}

// YoutubeTVSyncAccounts retrieves all the records using an executor.
func YoutubeTVSyncAccounts(mods ...qm.QueryMod) youtubeTVSyncAccountQuery {
	mods = append(mods, qm.From("\"youtube_tv_sync_accounts\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"youtube_tv_sync_accounts\".*"})
	}

	return youtubeTVSyncAccountQuery{q}
}

// FindYoutubeTVSyncAccount retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindYoutubeTVSyncAccount(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*YoutubeTVSyncAccount, error) {
	youtubeTVSyncAccountObj := &YoutubeTVSyncAccount{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"youtube_tv_sync_accounts\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, youtubeTVSyncAccountObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from youtube_tv_sync_accounts")
	}

	if err = youtubeTVSyncAccountObj.doAfterSelectHooks(ctx, exec); err != nil {
		return youtubeTVSyncAccountObj, err
	}

	return youtubeTVSyncAccountObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *YoutubeTVSyncAccount) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no youtube_tv_sync_accounts provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(youtubeTVSyncAccountColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	youtubeTVSyncAccountInsertCacheMut.RLock()
	cache, cached := youtubeTVSyncAccountInsertCache[key]
	youtubeTVSyncAccountInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			youtubeTVSyncAccountAllColumns,
			youtubeTVSyncAccountColumnsWithDefault,
			youtubeTVSyncAccountColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(youtubeTVSyncAccountType, youtubeTVSyncAccountMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(youtubeTVSyncAccountType, youtubeTVSyncAccountMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"youtube_tv_sync_accounts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"youtube_tv_sync_accounts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into youtube_tv_sync_accounts")
	}

	if !cached {
		youtubeTVSyncAccountInsertCacheMut.Lock()
		youtubeTVSyncAccountInsertCache[key] = cache
		youtubeTVSyncAccountInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the YoutubeTVSyncAccount.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *YoutubeTVSyncAccount) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	youtubeTVSyncAccountUpdateCacheMut.RLock()
	cache, cached := youtubeTVSyncAccountUpdateCache[key]
	youtubeTVSyncAccountUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			youtubeTVSyncAccountAllColumns,
			youtubeTVSyncAccountPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update youtube_tv_sync_accounts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"youtube_tv_sync_accounts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, youtubeTVSyncAccountPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(youtubeTVSyncAccountType, youtubeTVSyncAccountMapping, append(wl, youtubeTVSyncAccountPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update youtube_tv_sync_accounts row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for youtube_tv_sync_accounts")
	}

	if !cached {
		youtubeTVSyncAccountUpdateCacheMut.Lock()
		youtubeTVSyncAccountUpdateCache[key] = cache
		youtubeTVSyncAccountUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q youtubeTVSyncAccountQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for youtube_tv_sync_accounts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for youtube_tv_sync_accounts")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o YoutubeTVSyncAccountSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), youtubeTVSyncAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"youtube_tv_sync_accounts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, youtubeTVSyncAccountPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in youtubeTVSyncAccount slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all youtubeTVSyncAccount")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *YoutubeTVSyncAccount) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no youtube_tv_sync_accounts provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(youtubeTVSyncAccountColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	youtubeTVSyncAccountUpsertCacheMut.RLock()
	cache, cached := youtubeTVSyncAccountUpsertCache[key]
	youtubeTVSyncAccountUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			youtubeTVSyncAccountAllColumns,
			youtubeTVSyncAccountColumnsWithDefault,
			youtubeTVSyncAccountColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			youtubeTVSyncAccountAllColumns,
			youtubeTVSyncAccountPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert youtube_tv_sync_accounts, could not build update column list")
		}

		ret := strmangle.SetComplement(youtubeTVSyncAccountAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(youtubeTVSyncAccountPrimaryKeyColumns))
			copy(conflict, youtubeTVSyncAccountPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"youtube_tv_sync_accounts\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(youtubeTVSyncAccountType, youtubeTVSyncAccountMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(youtubeTVSyncAccountType, youtubeTVSyncAccountMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert youtube_tv_sync_accounts")
	}

	if !cached {
		youtubeTVSyncAccountUpsertCacheMut.Lock()
		youtubeTVSyncAccountUpsertCache[key] = cache
		youtubeTVSyncAccountUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single YoutubeTVSyncAccount record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *YoutubeTVSyncAccount) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no YoutubeTVSyncAccount provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), youtubeTVSyncAccountPrimaryKeyMapping)
	sql := "DELETE FROM \"youtube_tv_sync_accounts\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from youtube_tv_sync_accounts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for youtube_tv_sync_accounts")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q youtubeTVSyncAccountQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no youtubeTVSyncAccountQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from youtube_tv_sync_accounts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for youtube_tv_sync_accounts")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o YoutubeTVSyncAccountSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(youtubeTVSyncAccountBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), youtubeTVSyncAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"youtube_tv_sync_accounts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, youtubeTVSyncAccountPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from youtubeTVSyncAccount slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for youtube_tv_sync_accounts")
	}

	if len(youtubeTVSyncAccountAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *YoutubeTVSyncAccount) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindYoutubeTVSyncAccount(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *YoutubeTVSyncAccountSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := YoutubeTVSyncAccountSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), youtubeTVSyncAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"youtube_tv_sync_accounts\".* FROM \"youtube_tv_sync_accounts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, youtubeTVSyncAccountPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in YoutubeTVSyncAccountSlice")
	}

	*o = slice

	return nil
}

// YoutubeTVSyncAccountExists checks if the YoutubeTVSyncAccount row exists.
func YoutubeTVSyncAccountExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"youtube_tv_sync_accounts\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if youtube_tv_sync_accounts exists")
	}

	return exists, nil
}

// Exists checks if the YoutubeTVSyncAccount row exists.
func (o *YoutubeTVSyncAccount) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return YoutubeTVSyncAccountExists(ctx, exec, o.ID)
}
