// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// YoutubeSyncAccount is an object representing the database table.
type YoutubeSyncAccount struct {
	ID                       string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt                time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt                time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	UserID                   string      `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	RefreshTokenEnc          []byte      `boil:"refresh_token_enc" json:"refresh_token_enc" toml:"refresh_token_enc" yaml:"refresh_token_enc"`
	EncSecretHash            string      `boil:"enc_secret_hash" json:"enc_secret_hash" toml:"enc_secret_hash" yaml:"enc_secret_hash"`
	PlaylistID               null.String `boil:"playlist_id" json:"playlist_id,omitempty" toml:"playlist_id" yaml:"playlist_id,omitempty"`
	SyncEnabled              bool        `boil:"sync_enabled" json:"sync_enabled" toml:"sync_enabled" yaml:"sync_enabled"`
	LastFeedVideoPublishedAt null.Time   `boil:"last_feed_video_published_at" json:"last_feed_video_published_at,omitempty" toml:"last_feed_video_published_at" yaml:"last_feed_video_published_at,omitempty"`
	LastSyncedAt             null.Time   `boil:"last_synced_at" json:"last_synced_at,omitempty" toml:"last_synced_at" yaml:"last_synced_at,omitempty"`
	LastSyncAttemptAt        null.Time   `boil:"last_sync_attempt_at" json:"last_sync_attempt_at,omitempty" toml:"last_sync_attempt_at" yaml:"last_sync_attempt_at,omitempty"`
	LastError                string      `boil:"last_error" json:"last_error" toml:"last_error" yaml:"last_error"`

	R *youtubeSyncAccountR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L youtubeSyncAccountL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var YoutubeSyncAccountColumns = struct {
	ID                       string
	CreatedAt                string
	UpdatedAt                string
	UserID                   string
	RefreshTokenEnc          string
	EncSecretHash            string
	PlaylistID               string
	SyncEnabled              string
	LastFeedVideoPublishedAt string
	LastSyncedAt             string
	LastSyncAttemptAt        string
	LastError                string
}{
	ID:                       "id",
	CreatedAt:                "created_at",
	UpdatedAt:                "updated_at",
	UserID:                   "user_id",
	RefreshTokenEnc:          "refresh_token_enc",
	EncSecretHash:            "enc_secret_hash",
	PlaylistID:               "playlist_id",
	SyncEnabled:              "sync_enabled",
	LastFeedVideoPublishedAt: "last_feed_video_published_at",
	LastSyncedAt:             "last_synced_at",
	LastSyncAttemptAt:        "last_sync_attempt_at",
	LastError:                "last_error",
}

var YoutubeSyncAccountTableColumns = struct {
	ID                       string
	CreatedAt                string
	UpdatedAt                string
	UserID                   string
	RefreshTokenEnc          string
	EncSecretHash            string
	PlaylistID               string
	SyncEnabled              string
	LastFeedVideoPublishedAt string
	LastSyncedAt             string
	LastSyncAttemptAt        string
	LastError                string
}{
	ID:                       "youtube_sync_accounts.id",
	CreatedAt:                "youtube_sync_accounts.created_at",
	UpdatedAt:                "youtube_sync_accounts.updated_at",
	UserID:                   "youtube_sync_accounts.user_id",
	RefreshTokenEnc:          "youtube_sync_accounts.refresh_token_enc",
	EncSecretHash:            "youtube_sync_accounts.enc_secret_hash",
	PlaylistID:               "youtube_sync_accounts.playlist_id",
	SyncEnabled:              "youtube_sync_accounts.sync_enabled",
	LastFeedVideoPublishedAt: "youtube_sync_accounts.last_feed_video_published_at",
	LastSyncedAt:             "youtube_sync_accounts.last_synced_at",
	LastSyncAttemptAt:        "youtube_sync_accounts.last_sync_attempt_at",
	LastError:                "youtube_sync_accounts.last_error",
}

// Generated where

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var YoutubeSyncAccountWhere = struct {
	ID                       whereHelperstring
	CreatedAt                whereHelpertime_Time
	UpdatedAt                whereHelpertime_Time
	UserID                   whereHelperstring
	RefreshTokenEnc          whereHelper__byte
	EncSecretHash            whereHelperstring
	PlaylistID               whereHelpernull_String
	SyncEnabled              whereHelperbool
	LastFeedVideoPublishedAt whereHelpernull_Time
	LastSyncedAt             whereHelpernull_Time
	LastSyncAttemptAt        whereHelpernull_Time
	LastError                whereHelperstring
}{
	ID:                       whereHelperstring{field: "\"youtube_sync_accounts\".\"id\""},
	CreatedAt:                whereHelpertime_Time{field: "\"youtube_sync_accounts\".\"created_at\""},
	UpdatedAt:                whereHelpertime_Time{field: "\"youtube_sync_accounts\".\"updated_at\""},
	UserID:                   whereHelperstring{field: "\"youtube_sync_accounts\".\"user_id\""},
	RefreshTokenEnc:          whereHelper__byte{field: "\"youtube_sync_accounts\".\"refresh_token_enc\""},
	EncSecretHash:            whereHelperstring{field: "\"youtube_sync_accounts\".\"enc_secret_hash\""},
	PlaylistID:               whereHelpernull_String{field: "\"youtube_sync_accounts\".\"playlist_id\""},
	SyncEnabled:              whereHelperbool{field: "\"youtube_sync_accounts\".\"sync_enabled\""},
	LastFeedVideoPublishedAt: whereHelpernull_Time{field: "\"youtube_sync_accounts\".\"last_feed_video_published_at\""},
	LastSyncedAt:             whereHelpernull_Time{field: "\"youtube_sync_accounts\".\"last_synced_at\""},
	LastSyncAttemptAt:        whereHelpernull_Time{field: "\"youtube_sync_accounts\".\"last_sync_attempt_at\""},
	LastError:                whereHelperstring{field: "\"youtube_sync_accounts\".\"last_error\""},
}

// YoutubeSyncAccountRels is where relationship names are stored.
var YoutubeSyncAccountRels = struct {
	User string
}{
	User: "User",
}

// youtubeSyncAccountR is where relationships are stored.
type youtubeSyncAccountR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*youtubeSyncAccountR) NewStruct() *youtubeSyncAccountR {
	return &youtubeSyncAccountR{}
}

func (o *YoutubeSyncAccount) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *youtubeSyncAccountR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// youtubeSyncAccountL is where Load methods for each relationship are stored.
type youtubeSyncAccountL struct{}

var (
	youtubeSyncAccountAllColumns            = []string{"id", "created_at", "updated_at", "user_id", "refresh_token_enc", "enc_secret_hash", "playlist_id", "sync_enabled", "last_feed_video_published_at", "last_synced_at", "last_sync_attempt_at", "last_error"}
	youtubeSyncAccountColumnsWithoutDefault = []string{"id", "created_at", "updated_at", "user_id", "refresh_token_enc", "enc_secret_hash"}
	youtubeSyncAccountColumnsWithDefault    = []string{"playlist_id", "sync_enabled", "last_feed_video_published_at", "last_synced_at", "last_sync_attempt_at", "last_error"}
	youtubeSyncAccountPrimaryKeyColumns     = []string{"id"}
	youtubeSyncAccountGeneratedColumns      = []string{}
)

type (
	// YoutubeSyncAccountSlice is an alias for a slice of pointers to YoutubeSyncAccount.
	// This should almost always be used instead of []YoutubeSyncAccount.
	YoutubeSyncAccountSlice []*YoutubeSyncAccount
	// YoutubeSyncAccountHook is the signature for custom YoutubeSyncAccount hook methods
	YoutubeSyncAccountHook func(context.Context, boil.ContextExecutor, *YoutubeSyncAccount) error

	youtubeSyncAccountQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	youtubeSyncAccountType                 = reflect.TypeOf(&YoutubeSyncAccount{})
	youtubeSyncAccountMapping              = queries.MakeStructMapping(youtubeSyncAccountType)
	youtubeSyncAccountPrimaryKeyMapping, _ = queries.BindMapping(youtubeSyncAccountType, youtubeSyncAccountMapping, youtubeSyncAccountPrimaryKeyColumns)
	youtubeSyncAccountInsertCacheMut       sync.RWMutex
	youtubeSyncAccountInsertCache          = make(map[string]insertCache)
	youtubeSyncAccountUpdateCacheMut       sync.RWMutex
	youtubeSyncAccountUpdateCache          = make(map[string]updateCache)
	youtubeSyncAccountUpsertCacheMut       sync.RWMutex
	youtubeSyncAccountUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var youtubeSyncAccountAfterSelectMu sync.Mutex
var youtubeSyncAccountAfterSelectHooks []YoutubeSyncAccountHook

var youtubeSyncAccountBeforeInsertMu sync.Mutex
var youtubeSyncAccountBeforeInsertHooks []YoutubeSyncAccountHook
var youtubeSyncAccountAfterInsertMu sync.Mutex
var youtubeSyncAccountAfterInsertHooks []YoutubeSyncAccountHook

var youtubeSyncAccountBeforeUpdateMu sync.Mutex
var youtubeSyncAccountBeforeUpdateHooks []YoutubeSyncAccountHook
var youtubeSyncAccountAfterUpdateMu sync.Mutex
var youtubeSyncAccountAfterUpdateHooks []YoutubeSyncAccountHook

var youtubeSyncAccountBeforeDeleteMu sync.Mutex
var youtubeSyncAccountBeforeDeleteHooks []YoutubeSyncAccountHook
var youtubeSyncAccountAfterDeleteMu sync.Mutex
var youtubeSyncAccountAfterDeleteHooks []YoutubeSyncAccountHook

var youtubeSyncAccountBeforeUpsertMu sync.Mutex
var youtubeSyncAccountBeforeUpsertHooks []YoutubeSyncAccountHook
var youtubeSyncAccountAfterUpsertMu sync.Mutex
var youtubeSyncAccountAfterUpsertHooks []YoutubeSyncAccountHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *YoutubeSyncAccount) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeSyncAccountAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *YoutubeSyncAccount) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeSyncAccountBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *YoutubeSyncAccount) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeSyncAccountAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *YoutubeSyncAccount) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeSyncAccountBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *YoutubeSyncAccount) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeSyncAccountAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *YoutubeSyncAccount) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeSyncAccountBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *YoutubeSyncAccount) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeSyncAccountAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *YoutubeSyncAccount) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeSyncAccountBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *YoutubeSyncAccount) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range youtubeSyncAccountAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddYoutubeSyncAccountHook registers your hook function for all future operations.
func AddYoutubeSyncAccountHook(hookPoint boil.HookPoint, youtubeSyncAccountHook YoutubeSyncAccountHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		youtubeSyncAccountAfterSelectMu.Lock()
		youtubeSyncAccountAfterSelectHooks = append(youtubeSyncAccountAfterSelectHooks, youtubeSyncAccountHook)
		youtubeSyncAccountAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		youtubeSyncAccountBeforeInsertMu.Lock()
		youtubeSyncAccountBeforeInsertHooks = append(youtubeSyncAccountBeforeInsertHooks, youtubeSyncAccountHook)
		youtubeSyncAccountBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		youtubeSyncAccountAfterInsertMu.Lock()
		youtubeSyncAccountAfterInsertHooks = append(youtubeSyncAccountAfterInsertHooks, youtubeSyncAccountHook)
		youtubeSyncAccountAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		youtubeSyncAccountBeforeUpdateMu.Lock()
		youtubeSyncAccountBeforeUpdateHooks = append(youtubeSyncAccountBeforeUpdateHooks, youtubeSyncAccountHook)
		youtubeSyncAccountBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		youtubeSyncAccountAfterUpdateMu.Lock()
		youtubeSyncAccountAfterUpdateHooks = append(youtubeSyncAccountAfterUpdateHooks, youtubeSyncAccountHook)
		youtubeSyncAccountAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		youtubeSyncAccountBeforeDeleteMu.Lock()
		youtubeSyncAccountBeforeDeleteHooks = append(youtubeSyncAccountBeforeDeleteHooks, youtubeSyncAccountHook)
		youtubeSyncAccountBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		youtubeSyncAccountAfterDeleteMu.Lock()
		youtubeSyncAccountAfterDeleteHooks = append(youtubeSyncAccountAfterDeleteHooks, youtubeSyncAccountHook)
		youtubeSyncAccountAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		youtubeSyncAccountBeforeUpsertMu.Lock()
		youtubeSyncAccountBeforeUpsertHooks = append(youtubeSyncAccountBeforeUpsertHooks, youtubeSyncAccountHook)
		youtubeSyncAccountBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		youtubeSyncAccountAfterUpsertMu.Lock()
		youtubeSyncAccountAfterUpsertHooks = append(youtubeSyncAccountAfterUpsertHooks, youtubeSyncAccountHook)
		youtubeSyncAccountAfterUpsertMu.Unlock()
	}
}

// One returns a single youtubeSyncAccount record from the query.
func (q youtubeSyncAccountQuery) One(ctx context.Context, exec boil.ContextExecutor) (*YoutubeSyncAccount, error) {
	o := &YoutubeSyncAccount{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for youtube_sync_accounts")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all YoutubeSyncAccount records from the query.
func (q youtubeSyncAccountQuery) All(ctx context.Context, exec boil.ContextExecutor) (YoutubeSyncAccountSlice, error) {
	var o []*YoutubeSyncAccount

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to YoutubeSyncAccount slice")
	}

	if len(youtubeSyncAccountAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all YoutubeSyncAccount records in the query.
func (q youtubeSyncAccountQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count youtube_sync_accounts rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q youtubeSyncAccountQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if youtube_sync_accounts exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *YoutubeSyncAccount) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (youtubeSyncAccountL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeYoutubeSyncAccount any, mods queries.Applicator) error {
	var slice []*YoutubeSyncAccount
	var object *YoutubeSyncAccount

	if singular {
		var ok bool
		object, ok = maybeYoutubeSyncAccount.(*YoutubeSyncAccount)
		if !ok {
			object = new(YoutubeSyncAccount)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeYoutubeSyncAccount)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeYoutubeSyncAccount))
			}
		}
	} else {
		s, ok := maybeYoutubeSyncAccount.(*[]*YoutubeSyncAccount)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeYoutubeSyncAccount)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeYoutubeSyncAccount))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &youtubeSyncAccountR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &youtubeSyncAccountR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.YoutubeSyncAccount = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.YoutubeSyncAccount = local
				break
			}
		}
	}

	return nil
}

// SetUser of the youtubeSyncAccount to the related item.
// Sets o.R.User to related.
// Adds o to related.R.YoutubeSyncAccount.
func (o *YoutubeSyncAccount) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"youtube_sync_accounts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 0, youtubeSyncAccountPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &youtubeSyncAccountR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			YoutubeSyncAccount: o,
		}
	} else {
		related.R.YoutubeSyncAccount = o
	}

	return nil
}

// YoutubeSyncAccounts retrieves all the records using an executor.
func YoutubeSyncAccounts(mods ...qm.QueryMod) youtubeSyncAccountQuery {
	mods = append(mods, qm.From("\"youtube_sync_accounts\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"youtube_sync_accounts\".*"})
	}

	return youtubeSyncAccountQuery{q}
}

// FindYoutubeSyncAccount retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindYoutubeSyncAccount(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*YoutubeSyncAccount, error) {
	youtubeSyncAccountObj := &YoutubeSyncAccount{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"youtube_sync_accounts\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, youtubeSyncAccountObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from youtube_sync_accounts")
	}

	if err = youtubeSyncAccountObj.doAfterSelectHooks(ctx, exec); err != nil {
		return youtubeSyncAccountObj, err
	}

	return youtubeSyncAccountObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *YoutubeSyncAccount) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no youtube_sync_accounts provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(youtubeSyncAccountColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	youtubeSyncAccountInsertCacheMut.RLock()
	cache, cached := youtubeSyncAccountInsertCache[key]
	youtubeSyncAccountInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			youtubeSyncAccountAllColumns,
			youtubeSyncAccountColumnsWithDefault,
			youtubeSyncAccountColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(youtubeSyncAccountType, youtubeSyncAccountMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(youtubeSyncAccountType, youtubeSyncAccountMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"youtube_sync_accounts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"youtube_sync_accounts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into youtube_sync_accounts")
	}

	if !cached {
		youtubeSyncAccountInsertCacheMut.Lock()
		youtubeSyncAccountInsertCache[key] = cache
		youtubeSyncAccountInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the YoutubeSyncAccount.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *YoutubeSyncAccount) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	youtubeSyncAccountUpdateCacheMut.RLock()
	cache, cached := youtubeSyncAccountUpdateCache[key]
	youtubeSyncAccountUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			youtubeSyncAccountAllColumns,
			youtubeSyncAccountPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update youtube_sync_accounts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"youtube_sync_accounts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, youtubeSyncAccountPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(youtubeSyncAccountType, youtubeSyncAccountMapping, append(wl, youtubeSyncAccountPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update youtube_sync_accounts row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for youtube_sync_accounts")
	}

	if !cached {
		youtubeSyncAccountUpdateCacheMut.Lock()
		youtubeSyncAccountUpdateCache[key] = cache
		youtubeSyncAccountUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q youtubeSyncAccountQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for youtube_sync_accounts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for youtube_sync_accounts")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o YoutubeSyncAccountSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), youtubeSyncAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"youtube_sync_accounts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, youtubeSyncAccountPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in youtubeSyncAccount slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all youtubeSyncAccount")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *YoutubeSyncAccount) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no youtube_sync_accounts provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(youtubeSyncAccountColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	youtubeSyncAccountUpsertCacheMut.RLock()
	cache, cached := youtubeSyncAccountUpsertCache[key]
	youtubeSyncAccountUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			youtubeSyncAccountAllColumns,
			youtubeSyncAccountColumnsWithDefault,
			youtubeSyncAccountColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			youtubeSyncAccountAllColumns,
			youtubeSyncAccountPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert youtube_sync_accounts, could not build update column list")
		}

		ret := strmangle.SetComplement(youtubeSyncAccountAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(youtubeSyncAccountPrimaryKeyColumns))
			copy(conflict, youtubeSyncAccountPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"youtube_sync_accounts\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(youtubeSyncAccountType, youtubeSyncAccountMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(youtubeSyncAccountType, youtubeSyncAccountMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert youtube_sync_accounts")
	}

	if !cached {
		youtubeSyncAccountUpsertCacheMut.Lock()
		youtubeSyncAccountUpsertCache[key] = cache
		youtubeSyncAccountUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single YoutubeSyncAccount record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *YoutubeSyncAccount) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no YoutubeSyncAccount provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), youtubeSyncAccountPrimaryKeyMapping)
	sql := "DELETE FROM \"youtube_sync_accounts\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from youtube_sync_accounts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for youtube_sync_accounts")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q youtubeSyncAccountQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no youtubeSyncAccountQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from youtube_sync_accounts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for youtube_sync_accounts")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o YoutubeSyncAccountSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(youtubeSyncAccountBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), youtubeSyncAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"youtube_sync_accounts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, youtubeSyncAccountPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from youtubeSyncAccount slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for youtube_sync_accounts")
	}

	if len(youtubeSyncAccountAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *YoutubeSyncAccount) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindYoutubeSyncAccount(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *YoutubeSyncAccountSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := YoutubeSyncAccountSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), youtubeSyncAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"youtube_sync_accounts\".* FROM \"youtube_sync_accounts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, youtubeSyncAccountPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in YoutubeSyncAccountSlice")
	}

	*o = slice

	return nil
}

// YoutubeSyncAccountExists checks if the YoutubeSyncAccount row exists.
func YoutubeSyncAccountExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"youtube_sync_accounts\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if youtube_sync_accounts exists")
	}

	return exists, nil
}

// Exists checks if the YoutubeSyncAccount row exists.
func (o *YoutubeSyncAccount) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return YoutubeSyncAccountExists(ctx, exec, o.ID)
}
